### ISSUE TITLE
Tidal scrobbles don't yet seem to work

### ISSUE THREAD

**Issue by glennvanderstukken** [david-sabata/web-scrobbler#572] opened 2015-04-08 12:19 UTC
Hello,

The software recognises the website http://listen.tidalhifi.com/ as valid.
The software does not yet pick up on the songs I'm listening to, so I have to fill them in manually, but I recon that's a temporary thing.

Unfortunately, even after entering the songs manually, I still don't see the songs in my last.fm account.
Are there still known issues with Tidal?

Kind regards,

Glenn

**Comment by inverse** [comment] 2015-04-08 12:30
It sounds like the songs you are trying to listen to may not be in the last.fm database, which would be the reason for having to enter them in manually. 

Alternatively it could be matching the site wrong if they have updated their markup. I'm not as tidal user to be able to verify this but from quickly trying it out it seems to work.

Have you got a link to a page which is having this problem?

**Comment by glennvanderstukken** [comment] 2015-04-08 12:34
Hello, I'm listening to songs which are also in the last.fm database.
Here is the link to the song: http://listen.tidalhifi.com/track/10555021

**Comment by glennvanderstukken** [comment] 2015-04-08 12:47
Actually I also see that more popular music also isn't recognised, not on Tidal, nor Youtube or any other website. Perhaps another extension is blocking this one to work properly?

**Comment by david-sabata** [comment] 2015-06-20 11:19
@glennvanderstukken Are you still experiencing this issue? Can you please post the extension logs?
https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension

**Comment by alexesprit** [comment] 2017-01-01 09:30
@glennvanderstukken is Tidal scrobbling sill broken on the latest release?

**Comment by glennvanderstukken** [comment] 2017-01-03 09:34
Hello,

Not sure when exactly I opened that ticket, but I haven't been using Tidal for a very long time now. Therefore, I cannot check if the issue persists or not.

Kind regards
Glenn

________________________________
Van: Alexey <notifications@github.com>
Verzonden: zondag 1 januari 2017 10:30
Aan: david-sabata/web-scrobbler
CC: glennvanderstukken; Mention
Onderwerp: Re: [david-sabata/web-scrobbler] Tidal scrobbles don't yet seem to work (#572)


@glennvanderstukken<https://github.com/glennvanderstukken> is Tidal scrobbling sill broken on the latest release?

-

**Comment by alexesprit** [comment] 2017-01-03 17:29
I'll close it because it works for me and other users confirmed it (e.g. #1205).

**Closed by alexesprit** 2017-01-03 17:29 UTC
Labels: 1: NEEDS CONFIRM, 2: BUG, 3: CONNECTOR
