### ISSUE TITLE
Digitally Imported / DI.FM not scrobbling

### ISSUE THREAD

**Issue by danhughes01** [david-sabata/web-scrobbler#1398] opened 2017-09-10 18:47 UTC
Digitally Imported / DI.FM not scrobbling. 
Last.fm Scrobbler 1.68.1
Chrome Version 61.0.3163.79 (Official Build) (64-bit)
Windows Version	10.0.14393 Build 14393

### Steps to reproduce (for bugs)

1.  
2.  
3.  

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser name and version:

**Comment by alexesprit** [comment] 2017-09-12 04:02
Duplicate of #1379.

**Closed by alexesprit** 2017-09-12 04:02 UTC
