### ISSUE TITLE
play.google.com/music doesn't seem to work.

### ISSUE THREAD

**Issue by DawTaylor** [david-sabata/web-scrobbler#527] opened 2015-01-14 18:39 UTC
Trying to scrobble activity from Google Play Music but it doesn't works.

Are there any specific setting I should change in order to get it to work?

**Comment by BalooUriza** [comment] 2015-01-15 07:00
Also getting some inconsistency with Google Play; about 80% of the time it's not scrobbling, usually have to reauth 10-12+ times before it works.

**Comment by inverse** [comment] 2015-01-15 07:42
@BalooUriza have you tried re-installing the extension?

**Comment by david-sabata** [comment] 2015-01-15 10:29
Seems to work for me. What are the symptoms? Is there the icon in the browser address bar?

Does reauthing really work? It shouldn't make much difference.

Can you [post some logs](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension)?

**Comment by DawTaylor** [comment] 2015-01-15 10:56
Thanks for your time.

Reauth about 8 times and now it show a lastfm icon on the address bar. However the music wasn't scrobbled to my profile.

Logs. http://pastebin.com/dfuGSUk8

**Comment by BlakeIsBlake** [comment] 2015-01-16 20:24
Had this issue, reauthing seemed to fix it.

**Comment by DawTaylor** [comment] 2015-01-22 10:19
Unfortunately it didn't help me through.

**Comment by jaapz** [comment] 2015-01-26 12:38
I have the same problem, reauthing does not work. Do have the image in the address bar, but no actual scrobble.

**Comment by tellarin** [comment] 2015-01-28 09:02
Having a similar problem over here. Most recent Chrome build. It stops scrobbling intermittently not very often.

When it happens, the red icon is shown. Reloading the Google Music a couple times (<5) usually works. Otherwise, re-auth and re-launch browser works.

**Comment by NAUSHNIK52** [comment] 2015-03-15 10:25
Works OK for me. Chrome Beta.

**Comment by ottomatias** [comment] 2015-03-24 14:26
I have this issue too since few weeks. Youtube scrobbles fine but Google Music doesn't. Reauth doesn't help but reloading a couple of times seems to.

**Comment by Konc** [comment] 2015-04-16 08:06
Didn't work for me initially, but after a couple of reloads it started working.

**Comment by donalhunt** [comment] 2015-05-01 13:19
Also have the same issue. logs at http://pastebin.com/0KE8JNYu

**Comment by Yakovko** [comment] 2015-05-12 07:47
Have the same issue - looks like the web service is unavailable or API has changed. Logs: http://pastebin.com/5eCpVX6U

**Comment by tschieggm** [comment] 2015-07-07 03:59
I also consistently have this issue with google play music.

**Comment by inverse** [comment] 2015-07-07 17:15
related to #657

**Comment by david-sabata** [comment] 2015-07-28 16:31
Anyone still experiencing this issue?

**Comment by janbaykara** [comment] 2015-09-09 10:33
@david-sabata Perhaps something to put to bed?

**Comment by galeksandrp** [comment] 2015-09-10 13:08
Scrobbling is not starting when Play Music opened via ajax hyperlink on Google Play.

> cast sender errors in #664 means that opened site tried to connect chrome cast extension.

**Comment by daiyiwhale** [comment] 2015-09-21 23:03
Also not working for me!

**Comment by tellarin** [comment] 2015-10-10 05:51
I'm having this problem again. Now on Goolge Music and Youtube on Chorme on Windows 10.
Chrome on Windows 8.1 works fine in the same websites.

**Comment by inverse** [comment] 2016-11-06 18:04
Is this still an issue? one year on?

**Comment by alexesprit** [comment] 2017-01-01 09:38
I think all Google Play Music issues should be closed by following reasons:
1. There's no certain steps to reproduce in that issues.
2. #1176 is merged.

**Comment by alexesprit** [comment] 2017-01-16 14:52
Closed as outdated.

**Closed by alexesprit** 2017-01-16 14:52 UTC
Labels: 1: NEEDS CONFIRM, 2: BUG, 3: CONNECTOR, 4: OUTDATED
