### ISSUE TITLE
Feature request: parallel scrobbling to Libre.fm

### ISSUE THREAD

**Issue by keerah** [david-sabata/web-scrobbler#940] opened 2016-04-04 01:22 UTC
https://libre.fm

Suppose this feature is easy to implement

**Comment by inverse** [comment] 2016-04-04 09:23
Already proposed in PR #756

Related: #898

**Comment by c2c533c4f237** [comment] 2016-09-24 20:18
Hi, what is the status of this? I would also like to see libre.fm support.

**Comment by alexesprit** [comment] 2017-06-12 12:15
Closed as a duplicate of #37.

**Closed by alexesprit** 2017-06-12 12:15 UTC
Labels: 2: FEATURE, 3: CORE
