### ISSUE TITLE
TuneIn not scrobbling

### ISSUE THREAD

**Issue by SinnieOnFire** [david-sabata/web-scrobbler#1397] opened 2017-09-08 10:12 UTC
Can't scrobble from any station on TuneIn

### Expected behavior
Scrobble tracks played at TuneIn

### Current behavior
Extension detects that the site is TuneIn but does not detects music playing

<details> 
  <summary>Debug log</summary>
controller.js:80 Tab 443: state update: only currentTime has changed
inject.js:68 -- subsequent ajax navigation, the scripts are already injected
10controller.js:80 Tab 443: state update: only currentTime has changed
inject.js:68 -- subsequent ajax navigation, the scripts are already injected
5controller.js:80 Tab 443: state update: only currentTime has changed
inject.js:68 -- subsequent ajax navigation, the scripts are already injected
2controller.js:80 Tab 443: state update: only currentTime has changed
inject.js:68 -- subsequent ajax navigation, the scripts are already injected
54controller.js:80 Tab 443: state update: only currentTime has changed
controller.js:82 Tab 443: state update: {"track":null,"artist":"Космическая программа томных телочек","album":null,"uniqueID":"S6RO8aNWCm0","duration":123,"currentTime":123,"isPlaying":false,"trackArt":null}
controller.js:155 Tab 443: isPlaying state changed to false
main.js:275 Tab 443: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 443.
inject.js:68 -- subsequent ajax navigation, the scripts are already injected
main.js:275 Tab 393: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 393.
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 447: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
5inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 456: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
main.js:275 Tab 456: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 456.
19inject.js:68 -- subsequent ajax navigation, the scripts are already injected
main.js:275 Tab 447: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 447.
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 468: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
5inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 485: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
4inject.js:68 -- subsequent ajax navigation, the scripts are already injected
main.js:275 Tab 485: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 485.
inject.js:68 -- subsequent ajax navigation, the scripts are already injected
main.js:275 Tab 468: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 468.
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 487: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
10inject.js:68 -- subsequent ajax navigation, the scripts are already injected
main.js:275 Tab 487: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 487.
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 496: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
4inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 505: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
2inject.js:68 -- subsequent ajax navigation, the scripts are already injected
main.js:275 Tab 496: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 496.
20inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 547: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
main.js:275 Tab 547: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 547.
2inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 565: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
main.js:275 Tab 505: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 505.
inject.js:68 -- subsequent ajax navigation, the scripts are already injected
main.js:275 Tab 565: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 565.
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 578: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
3inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 580: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
main.js:275 Tab 578: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 578.
2inject.js:68 -- subsequent ajax navigation, the scripts are already injected
main.js:275 Tab 580: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 580.
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 582: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
18inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 589: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
main.js:275 Tab 589: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 589.
8inject.js:68 -- subsequent ajax navigation, the scripts are already injected
main.js:275 Tab 582: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 582.
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 606: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
5inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 608: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
2inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 610: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
6inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 612: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
main.js:275 Tab 612: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 612.
13inject.js:68 -- subsequent ajax navigation, the scripts are already injected
main.js:275 Tab 610: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 610.
main.js:275 Tab 606: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 606.
9inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 614: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
6inject.js:68 -- subsequent ajax navigation, the scripts are already injected
main.js:275 Tab 608: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 608.
5inject.js:68 -- subsequent ajax navigation, the scripts are already injected
main.js:275 Tab 614: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 614.
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 695: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
3inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 706: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
inject.js:68 -- subsequent ajax navigation, the scripts are already injected
main.js:275 Tab 695: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 695.
26inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 717: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
main.js:275 Tab 706: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 706.
4inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 719: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
main.js:275 Tab 719: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 719.
20inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 731: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
main.js:275 Tab 731: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 731.
8inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 735: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
15inject.js:68 -- subsequent ajax navigation, the scripts are already injected
main.js:275 Tab 717: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 717.
71inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 773: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
7inject.js:68 -- subsequent ajax navigation, the scripts are already injected
main.js:275 Tab 735: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 735.
5inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 786: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
main.js:275 Tab 773: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 773.
5inject.js:68 -- subsequent ajax navigation, the scripts are already injected
main.js:275 Tab 786: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 786.
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 790: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
20inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 814: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
3inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 816: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
main.js:275 Tab 790: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 790.
4inject.js:68 -- subsequent ajax navigation, the scripts are already injected
main.js:275 Tab 816: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 816.
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/tunein.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 820: created controller for connector: {"label":"TuneIn","matches":["*://tunein.com/*"],"js":["connectors/tunein.js"]}
6inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/tunein.js
inject.js:58 	injecting core/content/starter.js
main.js:275 Tab 820: remove controller
controller.js:458 Tab 820: created controller for connector: {"label":"TuneIn","matches":["*://tunein.com/*"],"js":["connectors/tunein.js"]}
3inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/tunein.js
inject.js:58 	injecting core/content/starter.js
main.js:275 Tab 820: remove controller
controller.js:458 Tab 820: created controller for connector: {"label":"TuneIn","matches":["*://tunein.com/*"],"js":["connectors/tunein.js"]}
2inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/tunein.js
inject.js:58 	injecting core/content/starter.js
main.js:275 Tab 820: remove controller
controller.js:458 Tab 820: created controller for connector: {"label":"TuneIn","matches":["*://tunein.com/*"],"js":["connectors/tunein.js"]}
7inject.js:68 -- subsequent ajax navigation, the scripts are already injected
main.js:275 Tab 814: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 814.
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 824: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
12inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 849: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
main.js:275 Tab 849: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 849.
7inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 851: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
main.js:275 Tab 851: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 851.
2inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 855: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
main.js:275 Tab 855: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 855.
6inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
controller.js:458 Tab 867: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/vk.js
inject.js:58 	injecting core/content/starter.js
main.js:275 Tab 867: remove controller
controller.js:458 Tab 867: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
main.js:275 Tab 867: remove controller
pageAction.js:68 While executing this.setPageAction: No tab with id: 867.
8inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/tunein.js
inject.js:58 	injecting core/content/starter.js
main.js:275 Tab 820: remove controller
controller.js:458 Tab 820: created controller for connector: {"label":"TuneIn","matches":["*://tunein.com/*"],"js":["connectors/tunein.js"]}
2inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/tunein.js
inject.js:58 	injecting core/content/starter.js
main.js:275 Tab 820: remove controller
controller.js:458 Tab 820: created controller for connector: {"label":"TuneIn","matches":["*://tunein.com/*"],"js":["connectors/tunein.js"]}
</details>

### Environment
* Version used:  1.68.1
* Browser name and version: Chrome 60.0.3112.113

**Comment by alexesprit** [comment] 2017-09-08 11:01
Looks like it's a duplicate of #1384.

P.S. Please next time use pastebin service or spoilers to post debug logs.

**Closed** 2017-09-08 16:47 UTC
Labels: 4: DUPLICATE
