### ISSUE TITLE
spotify doesn't scrobbler

### ISSUE THREAD

**Issue by anhbanbian** [david-sabata/web-scrobbler#1060] opened 2016-09-04 21:50 UTC
I have been refresh the tab and disable adblock. It doesn't fix anything.

**Comment by alexesprit** [comment] 2016-09-05 03:38
Works now for me. Have you tried to reauthenticate with Last.fm?

**Comment by anhbanbian** [comment] 2016-09-05 21:28
i have done everything. Delete the extension, remove all the cookie, and reauthenticate last.fm, delete adblock. I have done everything that can cause this problem.

**Comment by alexesprit** [comment] 2016-09-21 12:10
Can you check scrobbling on other websites? Is it works?
If scrobbling is broken on other websites too, it's could be great if you provide logs (see [this](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension) howto).

**Comment by nienna1** [comment] 2016-10-05 12:37
Hi, i have the same problem, add on recognises songs that are playing, but my last.fm profile doesn't scrobble anything:
![image](https://cloud.githubusercontent.com/assets/22637868/19113213/ea188646-8b08-11e6-8d57-21cc20938158.png)
![image](https://cloud.githubusercontent.com/assets/22637868/19113225/f9b54292-8b08-11e6-9ffe-0c6988e4d14d.png)

i tried deleting extension and reauthenticating with last.fm but nothing.

**Comment by nienna1** [comment] 2016-10-05 12:45
This is preview of the log:

> chromeStorage.js:100 chrome.storage.local = {"Core":{"appVersion":"1.58"},"LastFM":{"sessionID":"xxxxxf77cf22e7b70bc2c02bfc158bd1","sessionName":"knife party","token":null}}
> main.js:220 LastFM: Session ID xxxxxf77cf22e7b70bc2c02bfc158bd1
> inject.js:79 -- loaded for the first time, injecting the scripts
> inject.js:107 	injecting vendor/jquery-2.1.0.min.js
> inject.js:107 	injecting vendor/underscore-min.js
> inject.js:107 	injecting core/content/reactor.js
> inject.js:107 	injecting core/content/connector.js
> inject.js:107 	injecting connectors/v2/spotify-play.js
> inject.js:107 	injecting core/content/starter.js
> controller.js:325 Tab 14: created controller for connector: {"label":"Spotify","matches":["https://play.spotify.com/*"],"js":["connectors/v2/spotify-play.js"],"version":2}
> controller.js:93 Tab 14: new track state: {"track":"Come Home","artist":"Dismemberment Plan","album":null,"uniqueID":null,"duration":305,"currentTime":0,"isPlaying":false,"url":{"hash":"","search":"","pathname":"/artist/6fGIltjfZeNQ5jm6EjeDBz","port":"","hostname":"play.spotify.com","host":"play.spotify.com","protocol":"https:","origin":"https://play.spotify.com","href":"https://play.spotify.com/artist/6fGIltjfZeNQ5jm6EjeDBz","ancestorOrigins":{}},"trackArt":null}
> controller.js:101 Tab 14: new song detected: {"parsed":{"artist":"Dismemberment Plan","track":"Come Home","album":null,"uniqueID":null,"duration":305,"currentTime":null,"isPlaying":false,"trackArt":false,"url":{"hash":"","search":"","pathname":"/artist/6fGIltjfZeNQ5jm6EjeDBz","port":"","hostname":"play.spotify.com","host":"play.spotify.com","protocol":"https:","origin":"https://play.spotify.com","href":"https://play.spotify.com/artist/6fGIltjfZeNQ5jm6EjeDBz","ancestorOrigins":{}}},"processed":{"artist":"Dismemberment Plan","track":"Come Home","album":null,"duration":305},"metadata":{"userloved":false,"startTimestamp":1475670288,"url":{"hash":"","search":"","pathname":"/artist/6fGIltjfZeNQ5jm6EjeDBz","port":"","hostname":"play.spotify.com","host":"play.spotify.com","protocol":"https:","origin":"https://play.spotify.com","href":"https://play.spotify.com/artist/6fGIltjfZeNQ5jm6EjeDBz","ancestorOrigins":{}},"connector":{"label":"Spotify","matches":["https://play.spotify.com/*"],"js":["connectors/v2/spotify-play.js"],"version":2}},"flags":{"isProcessed":false,"isScrobbled":false,"isCorrectedByUser":false,"isLastfmValid":null,"isMarkedAsPlaying":false}}
> lastfm.js:213 L.FM response to https://ws.audioscrobbler.com/2.0/?method=track.getinfo&autocorrect=0&usern…mberment%20Plan&track=Come%20Home&api_key=d9bb1870d3269646f740544d9def2c95 : success
> <?xml version="1.0" encoding="UTF-8"?><lfm status="ok"><track><name>Come Home</name>
> <url>https://www.last.fm/music/Dismemberment+Plan/_/Come+Home</url>
> <duration>0</duration>
> <streamable fulltrack="0">0</streamable>
> <listeners>2</listeners>
> <playcount>2</playcount>
> <artist><name>Dismemberment Plan</name>
> <url>https://www.last.fm/music/Dismemberment+Plan</url>
> </artist>
> <userloved>0</userloved>
> <toptags/>
> </track>
> </lfm>
> musicbrainz-coverartarchive.js:19 Looking for album artwork via MusicBrainz
> controller.js:80 Tab 14: state update: only currentTime has changed
> http://coverartarchive.org/release/7c6e9f6e-3574-4a29-bada-177d0d12f0cf/front Failed to load resource: the server responded with a status of 404 (NOT FOUND)
> http://coverartarchive.org/release/96cb3abb-e3cc-311e-97c9-c90d7d4eeebf/front Failed to load resource: the server responded with a status of 404 (NOT FOUND)
> controller.js:150 Tab 14: song finished processing  {"parsed":{"artist":"Dismemberment Plan","track":"Come Home","album":null,"uniqueID":null,"duration":305,"currentTime":0,"isPlaying":false,"trackArt":"https://d3rt1990lpmkn.cloudfront.net/unbranded/242b24268baed7be86230bae158472af918d1f92","url":{"hash":"","search":"","pathname":"/artist/6fGIltjfZeNQ5jm6EjeDBz","port":"","hostname":"play.spotify.com","host":"play.spotify.com","protocol":"https:","origin":"https://play.spotify.com","href":"https://play.spotify.com/artist/6fGIltjfZeNQ5jm6EjeDBz","ancestorOrigins":{}}},"processed":{"artist":"Dismemberment Plan","track":"Come Home","album":null,"duration":0},"metadata":{"userloved":false,"startTimestamp":1475670288,"url":{"hash":"","search":"","pathname":"/artist/6fGIltjfZeNQ5jm6EjeDBz","port":"","hostname":"play.spotify.com","host":"play.spotify.com","protocol":"https:","origin":"https://play.spotify.com","href":"https://play.spotify.com/artist/6fGIltjfZeNQ5jm6EjeDBz","ancestorOrigins":{}},"connector":{"label":"Spotify","matches":["https://play.spotify.com/*"],"js":["connectors/v2/spotify-play.js"],"version":2},"artistUrl":"https://www.last.fm/music/Dismemberment+Plan","trackUrl":"https://www.last.fm/music/Dismemberment+Plan/_/Come+Home","artistThumbUrl":""},"flags":{"isProcessed":true,"isScrobbled":false,"isCorrectedByUser":false,"isLastfmValid":true,"isMarkedAsPlaying":false}}
> controller.js:200 Tab 14: the song will be scrobbled after 152.5 more seconds of playback
> 2inject.js:120 -- subsequent ajax navigation, the scripts are already injected
> controller.js:93 Tab 14: new track state: {"track":"Divers of the Dust","artist":"Marissa Nadler","album":null,"uniqueID":null,"duration":164,"currentTime":0,"isPlaying":true,"url":{"hash":"","search":"","pathname":"/artist/5zjaF8JUdylMWrA7AVo3hJ","port":"","hostname":"play.spotify.com","host":"play.spotify.com","protocol":"https:","origin":"https://play.spotify.com","href":"https://play.spotify.com/artist/5zjaF8JUdylMWrA7AVo3hJ","ancestorOrigins":{}},"trackArt":"https://d3rt1990lpmkn.cloudfront.net/unbranded/242b24268baed7be86230bae158472af918d1f92"}
> controller.js:101 Tab 14: new song detected: {"parsed":{"artist":"Marissa Nadler","track":"Divers of the Dust","album":null,"uniqueID":null,"duration":164,"currentTime":null,"isPlaying":true,"trackArt":"https://d3rt1990lpmkn.cloudfront.net/unbranded/242b24268baed7be86230bae158472af918d1f92","url":{"hash":"","search":"","pathname":"/artist/5zjaF8JUdylMWrA7AVo3hJ","port":"","hostname":"play.spotify.com","host":"play.spotify.com","protocol":"https:","origin":"https://play.spotify.com","href":"https://play.spotify.com/artist/5zjaF8JUdylMWrA7AVo3hJ","ancestorOrigins":{}}},"processed":{"artist":"Marissa Nadler","track":"Divers of the Dust","album":null,"duration":164},"metadata":{"userloved":false,"startTimestamp":1475670320,"url":{"hash":"","search":"","pathname":"/artist/5zjaF8JUdylMWrA7AVo3hJ","port":"","hostname":"play.spotify.com","host":"play.spotify.com","protocol":"https:","origin":"https://play.spotify.com","href":"https://play.spotify.com/artist/5zjaF8JUdylMWrA7AVo3hJ","ancestorOrigins":{}},"connector":{"label":"Spotify","matches":["https://play.spotify.com/*"],"js":["connectors/v2/spotify-play.js"],"version":2}},"flags":{"isProcessed":false,"isScrobbled":false,"isCorrectedByUser":false,"isLastfmValid":null,"isMarkedAsPlaying":false}}
> controller.js:80 Tab 14: state update: only currentTime has changed
> lastfm.js:213 L.FM response to https://ws.audioscrobbler.com/2.0/?method=track.getinfo&autocorrect=0&usern…er&track=Divers%20of%20the%20Dust&api_key=d9bb1870d3269646f740544d9def2c95 : success
> <?xml version="1.0" encoding="UTF-8"?><lfm status="ok"><track><name>Divers of the Dust</name>
> <url>https://www.last.fm/music/Marissa+Nadler/_/Divers+of+the+Dust</url>
> <duration>0</duration>
> <streamable fulltrack="0">0</streamable>
> <listeners>6826</listeners>
> <playcount>18008</playcount>
> <artist><name>Marissa Nadler</name>
> <mbid>06ae569e-0b5b-4cd7-aded-98c3ad743ca3</mbid>
> <url>https://www.last.fm/music/Marissa+Nadler</url>
> </artist>
> <userplaycount>2</userplaycount>
> <userloved>0</userloved>
> <toptags/>
> </track>
> </lfm>
> musicbrainz-coverartarchive.js:13 Using local/parsed artwork
> controller.js:150 Tab 14: song finished processing  {"parsed":{"artist":"Marissa Nadler","track":"Divers of the Dust","album":null,"uniqueID":null,"duration":164,"currentTime":0,"isPlaying":true,"trackArt":"https://d3rt1990lpmkn.cloudfront.net/unbranded/8405bf7dc62cfb22aaf2b9674ac20932af690ca2","url":{"hash":"","search":"","pathname":"/artist/5zjaF8JUdylMWrA7AVo3hJ","port":"","hostname":"play.spotify.com","host":"play.spotify.com","protocol":"https:","origin":"https://play.spotify.com","href":"https://play.spotify.com/artist/5zjaF8JUdylMWrA7AVo3hJ","ancestorOrigins":{}}},"processed":{"artist":"Marissa Nadler","track":"Divers of the Dust","album":null,"duration":0},"metadata":{"userloved":false,"startTimestamp":1475670320,"url":{"hash":"","search":"","pathname":"/artist/5zjaF8JUdylMWrA7AVo3hJ","port":"","hostname":"play.spotify.com","host":"play.spotify.com","protocol":"https:","origin":"https://play.spotify.com","href":"https://play.spotify.com/artist/5zjaF8JUdylMWrA7AVo3hJ","ancestorOrigins":{}},"connector":{"label":"Spotify","matches":["https://play.spotify.com/*"],"js":["connectors/v2/spotify-play.js"],"version":2},"artistUrl":"https://www.last.fm/music/Marissa+Nadler","trackUrl":"https://www.last.fm/music/Marissa+Nadler/_/Divers+of+the+Dust","artistThumbUrl":"https://d3rt1990lpmkn.cloudfront.net/unbranded/8405bf7dc62cfb22aaf2b9674ac20932af690ca2"},"flags":{"isProcessed":true,"isScrobbled":false,"isCorrectedByUser":false,"isLastfmValid":true,"isMarkedAsPlaying":false}}
> controller.js:200 Tab 14: the song will be scrobbled after 82 more seconds of playback
> lastfm.js:213 L.FM response to https://ws.audioscrobbler.com/2.0/?method=track.updatenowplaying&track=Dive…=9840bf77cf22e7b70bc2c02bfc158bd1&api_sig=6a51d2e87a7721956dc4a5743880b775 : success
> <?xml version="1.0" encoding="utf-8"?><lfm status="ok">
>   <nowplaying>
>     <track corrected="0">Divers of the Dust</track>
>     <artist corrected="0">Marissa Nadler</artist>
>     <album corrected="0"/>
>     <albumArtist corrected="0"/>
>     <ignoredMessage code="0"/>
>   </nowplaying>
> </lfm>
> controller.js:234 Tab 14: song set as now playing: true
> 5controller.js:80 Tab 14: state update: only currentTime has changed
> notifications.js:181 Notification onClicked: 12C9B17F-B092-4797-8214-E1FEFEE46889
> controller.js:80 Tab 14: state update: only currentTime has changed
> 2notifications.js:181 Notification onClicked: 12C9B17F-B092-4797-8214-E1FEFEE46889
> 71controller.js:80 Tab 14: state update: only currentTime has changed
> controller.js:247 Tab 14: scrobbling song Marissa Nadler - Divers of the Dust
> lastfm.js:213 L.FM response to https://ws.audioscrobbler.com/2.0/?method=track.scrobble&timestamp[0]=14756…=9840bf77cf22e7b70bc2c02bfc158bd1&api_sig=c0c183c23d7cd57824efa26141e81a81 : success
> <?xml version="1.0" encoding="utf-8"?><lfm status="ok">
>   <scrobbles ignored="0" accepted="1">
>     <scrobble>
>       <track corrected="0">Divers of the Dust</track>
>       <artist corrected="0">Marissa Nadler</artist>
>       <album corrected="0"/>
>       <albumArtist corrected="0"/>
>       <timestamp>1475670320</timestamp>
>       <ignoredMessage code="0"/>
>     </scrobble>
>   </scrobbles>
> </lfm>
> controller.js:251 Tab 14: scrobbled successfully
> 32controller.js:80 Tab 14: state update: only currentTime has changed
> lastfm.js:213 L.FM response to https://ws.audioscrobbler.com/2.0/?method=track.love&track=Divers%20of%20th…=9840bf77cf22e7b70bc2c02bfc158bd1&api_sig=5555a04f72852404d4bd342d834db4d4 : success
> <?xml version="1.0" encoding="UTF-8"?><lfm status="ok"/>
> 30controller.js:80 Tab 14: state update: only currentTime has changed
> 8controller.js:80 Tab 14: state update: only currentTime has changed
> 6controller.js:80 Tab 14: state update: only currentTime has changed
> controller.js:82 Tab 14: state update: {"track":"Divers of the Dust","artist":"Marissa Nadler","album":null,"uniqueID":null,"duration":164,"currentTime":164,"isPlaying":false,"url":{"hash":"","search":"","pathname":"/artist/5zjaF8JUdylMWrA7AVo3hJ","port":"","hostname":"play.spotify.com","host":"play.spotify.com","protocol":"https:","origin":"https://play.spotify.com","href":"https://play.spotify.com/artist/5zjaF8JUdylMWrA7AVo3hJ","ancestorOrigins":{}},"trackArt":"https://d3rt1990lpmkn.cloudfront.net/unbranded/8405bf7dc62cfb22aaf2b9674ac20932af690ca2"}
> controller.js:130 Tab 14: isPlaying state changed to false
> controller.js:93 Tab 14: new track state: {"track":"Skyscraper","artist":"Marissa Nadler","album":null,"uniqueID":null,"duration":247,"currentTime":0,"isPlaying":true,"url":{"hash":"","search":"","pathname":"/artist/5zjaF8JUdylMWrA7AVo3hJ","port":"","hostname":"play.spotify.com","host":"play.spotify.com","protocol":"https:","origin":"https://play.spotify.com","href":"https://play.spotify.com/artist/5zjaF8JUdylMWrA7AVo3hJ","ancestorOrigins":{}},"trackArt":"https://d3rt1990lpmkn.cloudfront.net/unbranded/8405bf7dc62cfb22aaf2b9674ac20932af690ca2"}
> controller.js:101 Tab 14: new song detected: {"parsed":{"artist":"Marissa Nadler","track":"Skyscraper","album":null,"uniqueID":null,"duration":247,"currentTime":null,"isPlaying":true,"trackArt":"https://d3rt1990lpmkn.cloudfront.net/unbranded/8405bf7dc62cfb22aaf2b9674ac20932af690ca2","url":{"hash":"","search":"","pathname":"/artist/5zjaF8JUdylMWrA7AVo3hJ","port":"","hostname":"play.spotify.com","host":"play.spotify.com","protocol":"https:","origin":"https://play.spotify.com","href":"https://play.spotify.com/artist/5zjaF8JUdylMWrA7AVo3hJ","ancestorOrigins":{}}},"processed":{"artist":"Marissa Nadler","track":"Skyscraper","album":null,"duration":247},"metadata":{"userloved":false,"startTimestamp":1475670505,"url":{"hash":"","search":"","pathname":"/artist/5zjaF8JUdylMWrA7AVo3hJ","port":"","hostname":"play.spotify.com","host":"play.spotify.com","protocol":"https:","origin":"https://play.spotify.com","href":"https://play.spotify.com/artist/5zjaF8JUdylMWrA7AVo3hJ","ancestorOrigins":{}},"connector":{"label":"Spotify","matches":["https://play.spotify.com/*"],"js":["connectors/v2/spotify-play.js"],"version":2}},"flags":{"isProcessed":false,"isScrobbled":false,"isCorrectedByUser":false,"isLastfmValid":null,"isMarkedAsPlaying":false}}
> lastfm.js:213 L.FM response to https://ws.audioscrobbler.com/2.0/?method=track.getinfo&autocorrect=0&usern…Marissa%20Nadler&track=Skyscraper&api_key=d9bb1870d3269646f740544d9def2c95 : success
> <?xml version="1.0" encoding="UTF-8"?><lfm status="ok"><track><name>Skyscraper</name>
> <url>https://www.last.fm/music/Marissa+Nadler/_/Skyscraper</url>
> <duration>247000</duration>
> <streamable fulltrack="0">0</streamable>
> <listeners>5544</listeners>
> <playcount>14207</playcount>
> <artist><name>Marissa Nadler</name>
> <mbid>06ae569e-0b5b-4cd7-aded-98c3ad743ca3</mbid>
> <url>https://www.last.fm/music/Marissa+Nadler</url>
> </artist>
> <userplaycount>2</userplaycount>
> <userloved>0</userloved>
> <toptags/>
> </track>
> </lfm>
> musicbrainz-coverartarchive.js:13 Using local/parsed artwork
> controller.js:150 Tab 14: song finished processing  {"parsed":{"artist":"Marissa Nadler","track":"Skyscraper","album":null,"uniqueID":null,"duration":247,"currentTime":null,"isPlaying":true,"trackArt":"https://d3rt1990lpmkn.cloudfront.net/unbranded/8405bf7dc62cfb22aaf2b9674ac20932af690ca2","url":{"hash":"","search":"","pathname":"/artist/5zjaF8JUdylMWrA7AVo3hJ","port":"","hostname":"play.spotify.com","host":"play.spotify.com","protocol":"https:","origin":"https://play.spotify.com","href":"https://play.spotify.com/artist/5zjaF8JUdylMWrA7AVo3hJ","ancestorOrigins":{}}},"processed":{"artist":"Marissa Nadler","track":"Skyscraper","album":null,"duration":247},"metadata":{"userloved":false,"startTimestamp":1475670505,"url":{"hash":"","search":"","pathname":"/artist/5zjaF8JUdylMWrA7AVo3hJ","port":"","hostname":"play.spotify.com","host":"play.spotify.com","protocol":"https:","origin":"https://play.spotify.com","href":"https://play.spotify.com/artist/5zjaF8JUdylMWrA7AVo3hJ","ancestorOrigins":{}},"connector":{"label":"Spotify","matches":["https://play.spotify.com/*"],"js":["connectors/v2/spotify-play.js"],"version":2},"artistUrl":"https://www.last.fm/music/Marissa+Nadler","trackUrl":"https://www.last.fm/music/Marissa+Nadler/_/Skyscraper","artistThumbUrl":"https://d3rt1990lpmkn.cloudfront.net/unbranded/8405bf7dc62cfb22aaf2b9674ac20932af690ca2"},"flags":{"isProcessed":true,"isScrobbled":false,"isCorrectedByUser":false,"isLastfmValid":true,"isMarkedAsPlaying":false}}
> controller.js:200 Tab 14: the song will be scrobbled after 123.5 more seconds of playback
> lastfm.js:213 L.FM response to https://ws.audioscrobbler.com/2.0/?method=track.updatenowplaying&track=Skys…=9840bf77cf22e7b70bc2c02bfc158bd1&api_sig=cdb58d408d00840bf662850369651fc9 : success
> <?xml version="1.0" encoding="utf-8"?><lfm status="ok">
>   <nowplaying>
>     <track corrected="0">Skyscraper</track>
>     <artist corrected="0">Marissa Nadler</artist>
>     <album corrected="0"/>
>     <albumArtist corrected="0"/>
>     <ignoredMessage code="0"/>
>   </nowplaying>
> </lfm>
> controller.js:234 Tab 14: song set as now playing: true
> controller.js:82 Tab 14: state update: {"track":"Skyscraper","artist":"Marissa Nadler","album":null,"uniqueID":null,"duration":247,"currentTime":0,"isPlaying":false,"url":{"hash":"","search":"","pathname":"/artist/5zjaF8JUdylMWrA7AVo3hJ","port":"","hostname":"play.spotify.com","host":"play.spotify.com","protocol":"https:","origin":"https://play.spotify.com","href":"https://play.spotify.com/artist/5zjaF8JUdylMWrA7AVo3hJ","ancestorOrigins":{}},"trackArt":"https://d3rt1990lpmkn.cloudfront.net/unbranded/8405bf7dc62cfb22aaf2b9674ac20932af690ca2"}
> controller.js:130 Tab 14: isPlaying state changed to false
> controller.js:82 Tab 14: state update: {"track":"Skyscraper","artist":"Marissa Nadler","album":null,"uniqueID":null,"duration":247,"currentTime":0,"isPlaying":true,"url":{"hash":"","search":"","pathname":"/artist/5zjaF8JUdylMWrA7AVo3hJ","port":"","hostname":"play.spotify.com","host":"play.spotify.com","protocol":"https:","origin":"https://play.spotify.com","href":"https://play.spotify.com/artist/5zjaF8JUdylMWrA7AVo3hJ","ancestorOrigins":{}},"trackArt":"https://d3rt1990lpmkn.cloudfront.net/unbranded/8405bf7dc62cfb22aaf2b9674ac20932af690ca2"}
> controller.js:130 Tab 14: isPlaying state changed to true
> 60controller.js:80 Tab 14: state update: only currentTime has changed
> notifications.js:181 Notification onClicked: 4CAE9FE8-DA26-4D0A-B1E0-B6265598C515
> 55controller.js:80 Tab 14: state update: only currentTime has changed
> controller.js:247 Tab 14: scrobbling song Marissa Nadler - Skyscraper
> lastfm.js:213 L.FM response to https://ws.audioscrobbler.com/2.0/?method=track.scrobble&timestamp[0]=14756…=d4731546b5c85c5d856f894d488cbb44&api_sig=da6571e7b7473dad53711bca00796307 : success
> <?xml version="1.0" encoding="utf-8"?><lfm status="ok">
>   <scrobbles ignored="0" accepted="1">
>     <scrobble>
>       <track corrected="0">Skyscraper</track>
>       <artist corrected="0">Marissa Nadler</artist>
>       <album corrected="0"/>
>       <albumArtist corrected="0"/>
>       <timestamp>1475670505</timestamp>
>       <ignoredMessage code="0"/>
>     </scrobble>
>   </scrobbles>
> </lfm>
> controller.js:251 Tab 14: scrobbled successfully
> 118controller.js:80 Tab 14: state update: only currentTime has changed
> controller.js:82 Tab 14: state update: {"track":"Skyscraper","artist":"Marissa Nadler","album":null,"uniqueID":null,"duration":247,"currentTime":247,"isPlaying":false,"url":{"hash":"","search":"","pathname":"/artist/5zjaF8JUdylMWrA7AVo3hJ","port":"","hostname":"play.spotify.com","host":"play.spotify.com","protocol":"https:","origin":"https://play.spotify.com","href":"https://play.spotify.com/artist/5zjaF8JUdylMWrA7AVo3hJ","ancestorOrigins":{}},"trackArt":"https://d3rt1990lpmkn.cloudfront.net/unbranded/8405bf7dc62cfb22aaf2b9674ac20932af690ca2"}
> controller.js:130 Tab 14: isPlaying state changed to false
> controller.js:93 Tab 14: new track state: {"track":"Hungry Is the Ghost","artist":"Marissa Nadler","album":null,"uniqueID":null,"duration":376,"currentTime":0,"isPlaying":true,"url":{"hash":"","search":"","pathname":"/artist/5zjaF8JUdylMWrA7AVo3hJ","port":"","hostname":"play.spotify.com","host":"play.spotify.com","protocol":"https:","origin":"https://play.spotify.com","href":"https://play.spotify.com/artist/5zjaF8JUdylMWrA7AVo3hJ","ancestorOrigins":{}},"trackArt":"https://d3rt1990lpmkn.cloudfront.net/unbranded/8405bf7dc62cfb22aaf2b9674ac20932af690ca2"}
> controller.js:101 Tab 14: new song detected: {"parsed":{"artist":"Marissa Nadler","track":"Hungry Is the Ghost","album":null,"uniqueID":null,"duration":376,"currentTime":null,"isPlaying":true,"trackArt":"https://d3rt1990lpmkn.cloudfront.net/unbranded/8405bf7dc62cfb22aaf2b9674ac20932af690ca2","url":{"hash":"","search":"","pathname":"/artist/5zjaF8JUdylMWrA7AVo3hJ","port":"","hostname":"play.spotify.com","host":"play.spotify.com","protocol":"https:","origin":"https://play.spotify.com","href":"https://play.spotify.com/artist/5zjaF8JUdylMWrA7AVo3hJ","ancestorOrigins":{}}},"processed":{"artist":"Marissa Nadler","track":"Hungry Is the Ghost","album":null,"duration":376},"metadata":{"userloved":false,"startTimestamp":1475670756,"url":{"hash":"","search":"","pathname":"/artist/5zjaF8JUdylMWrA7AVo3hJ","port":"","hostname":"play.spotify.com","host":"play.spotify.com","protocol":"https:","origin":"https://play.spotify.com","href":"https://play.spotify.com/artist/5zjaF8JUdylMWrA7AVo3hJ","ancestorOrigins":{}},"connector":{"label":"Spotify","matches":["https://play.spotify.com/*"],"js":["connectors/v2/spotify-play.js"],"version":2}},"flags":{"isProcessed":false,"isScrobbled":false,"isCorrectedByUser":false,"isLastfmValid":null,"isMarkedAsPlaying":false}}
> lastfm.js:213 L.FM response to https://ws.audioscrobbler.com/2.0/?method=track.getinfo&autocorrect=0&usern…r&track=Hungry%20Is%20the%20Ghost&api_key=d9bb1870d3269646f740544d9def2c95 : success
> <?xml version="1.0" encoding="UTF-8"?><lfm status="ok"><track><name>Hungry Is the Ghost</name>
> <url>https://www.last.fm/music/Marissa+Nadler/_/Hungry+Is+the+Ghost</url>
> <duration>376000</duration>
> <streamable fulltrack="0">0</streamable>
> <listeners>5214</listeners>
> <playcount>13663</playcount>
> <artist><name>Marissa Nadler</name>
> <mbid>06ae569e-0b5b-4cd7-aded-98c3ad743ca3</mbid>
> <url>https://www.last.fm/music/Marissa+Nadler</url>
> </artist>
> <userplaycount>2</userplaycount>
> <userloved>0</userloved>
> <toptags/>
> </track>
> </lfm>
> musicbrainz-coverartarchive.js:13 Using local/parsed artwork
> controller.js:150 Tab 14: song finished processing  {"parsed":{"artist":"Marissa Nadler","track":"Hungry Is the Ghost","album":null,"uniqueID":null,"duration":376,"currentTime":null,"isPlaying":true,"trackArt":"https://d3rt1990lpmkn.cloudfront.net/unbranded/8405bf7dc62cfb22aaf2b9674ac20932af690ca2","url":{"hash":"","search":"","pathname":"/artist/5zjaF8JUdylMWrA7AVo3hJ","port":"","hostname":"play.spotify.com","host":"play.spotify.com","protocol":"https:","origin":"https://play.spotify.com","href":"https://play.spotify.com/artist/5zjaF8JUdylMWrA7AVo3hJ","ancestorOrigins":{}}},"processed":{"artist":"Marissa Nadler","track":"Hungry Is the Ghost","album":null,"duration":376},"metadata":{"userloved":false,"startTimestamp":1475670756,"url":{"hash":"","search":"","pathname":"/artist/5zjaF8JUdylMWrA7AVo3hJ","port":"","hostname":"play.spotify.com","host":"play.spotify.com","protocol":"https:","origin":"https://play.spotify.com","href":"https://play.spotify.com/artist/5zjaF8JUdylMWrA7AVo3hJ","ancestorOrigins":{}},"connector":{"label":"Spotify","matches":["https://play.spotify.com/*"],"js":["connectors/v2/spotify-play.js"],"version":2},"artistUrl":"https://www.last.fm/music/Marissa+Nadler","trackUrl":"https://www.last.fm/music/Marissa+Nadler/_/Hungry+Is+the+Ghost","artistThumbUrl":"https://d3rt1990lpmkn.cloudfront.net/unbranded/8405bf7dc62cfb22aaf2b9674ac20932af690ca2"},"flags":{"isProcessed":true,"isScrobbled":false,"isCorrectedByUser":false,"isLastfmValid":true,"isMarkedAsPlaying":false}}
> controller.js:200 Tab 14: the song will be scrobbled after 188 more seconds of playback
> lastfm.js:213 L.FM response to https://ws.audioscrobbler.com/2.0/?method=track.updatenowplaying&track=Hung…=d4731546b5c85c5d856f894d488cbb44&api_sig=6240492caf22c05d36c829d76bac1616 : success
> <?xml version="1.0" encoding="utf-8"?><lfm status="ok">
>   <nowplaying>
>     <track corrected="0">Hungry Is the Ghost</track>
>     <artist corrected="0">Marissa Nadler</artist>
>     <album corrected="0"/>
>     <albumArtist corrected="0"/>
>     <ignoredMessage code="0"/>
>   </nowplaying>
> </lfm>
> controller.js:234 Tab 14: song set as now playing: true
> 177controller.js:80 Tab 14: state update: only currentTime has changed
> controller.js:247 Tab 14: scrobbling song Marissa Nadler - Hungry Is the Ghost
> lastfm.js:213 L.FM response to https://ws.audioscrobbler.com/2.0/?method=track.scrobble&timestamp[0]=14756…=d4731546b5c85c5d856f894d488cbb44&api_sig=5215f1a2b2f8a5f84ab6f3d32d789f0b : success
> <?xml version="1.0" encoding="utf-8"?><lfm status="ok">
>   <scrobbles ignored="0" accepted="1">
>     <scrobble>
>       <track corrected="0">Hungry Is the Ghost</track>
>       <artist corrected="0">Marissa Nadler</artist>
>       <album corrected="0"/>
>       <albumArtist corrected="0"/>
>       <timestamp>1475670756</timestamp>
>       <ignoredMessage code="0"/>
>     </scrobble>
>   </scrobbles>
> </lfm>
> controller.js:251 Tab 14: scrobbled successfully
> 161controller.js:80 Tab 14: state update: only currentTime has changed
> 13controller.js:80 Tab 14: state update: only currentTime has changed
> controller.js:82 Tab 14: state update: {"track":"Hungry Is the Ghost","artist":"Marissa Nadler","album":null,"uniqueID":null,"duration":376,"currentTime":376,"isPlaying":false,"url":{"hash":"","search":"","pathname":"/artist/5zjaF8JUdylMWrA7AVo3hJ","port":"","hostname":"play.spotify.com","host":"play.spotify.com","protocol":"https:","origin":"https://play.spotify.com","href":"https://play.spotify.com/artist/5zjaF8JUdylMWrA7AVo3hJ","ancestorOrigins":{}},"trackArt":"https://d3rt1990lpmkn.cloudfront.net/unbranded/8405bf7dc62cfb22aaf2b9674ac20932af690ca2"}
> controller.js:130 Tab 14: isPlaying state changed to false

**Comment by alexesprit** [comment] 2016-10-05 13:01
@nienna1 According to provided logs the extension scrobbled tracks succesfully. Maybe it's something wrong on Last.fm's side.
Have you tried to scrobble the music from another sources (like Youtube, Soundcloud etc)?

**Comment by nienna1** [comment] 2016-10-05 13:16
@alexesprit yes, that's how it looked to me too.

I just tried scrobbling from youtube, and it's the same. add-on recognises it, but nothing on my last.fm account. :(

**Comment by alexesprit** [comment] 2016-10-05 13:20
@nienna1 strange things happen. Can you try to scrobble the music again later? Maybe it's just temporary  Last.fm problem.

**Comment by nienna1** [comment] 2016-10-05 13:24
@alexesprit i will, but this is how things are for the last week, it's only today that i tried fixing it, so i doubt anything will change.

**Comment by alexesprit** [comment] 2016-12-21 16:33
@nienna1 is the situation with Spotify scrobbling still the same?

**Comment by nienna1** [comment] 2016-12-27 08:22
hi @alexesprit, thanks for your worry. when i listen to music on spotify on my computer on work, it doesn't scrobble - i have UK based IP address there because i work for UK oranisation, so maybe it's because of that...?
i thought it's only there, but right now i'm listening at home on spotify and it's still not working:
![screen shot 2016-12-27 at 09 20 36](https://cloud.githubusercontent.com/assets/22637868/21495116/01628308-cc16-11e6-892c-70c48992fff1.png)

**Comment by alexesprit** [comment] 2016-12-27 08:24
Could you please open developer console (Ctrl+Shift+I, then select 'Console' tab) and send me its content (but please use pastebin services instead of pasting the content here)?

**Comment by nienna1** [comment] 2016-12-27 08:32
here it is: http://pastebin.com/nrdL7fi1

**Comment by alexesprit** [comment] 2016-12-27 08:35
@nienna1 hmm, ok. Could you also provide the content of background page log after doing these steps:
1. Open browser.
2. Open Spotify.
3. Play some song.
4. Collect logs and send them.

**Comment by nienna1** [comment] 2016-12-27 09:05
i restarted chrome and it's working now! once i get back to my office i'll let you know how are things doing there. thank you once again for all of your support.

**Comment by janbaykara** [comment] 2016-12-31 02:45
I'm almost definite Spotify has Last.fm scrobbling built-in?

**Comment by alexesprit** [comment] 2017-03-12 14:42
I'm closing this issue because looks like new Spotify player is default for most users; the issue is not related to current web player.

**Closed by alexesprit** 2017-03-12 14:42 UTC
Labels: 1: NEEDS CONFIRM, 2: BUG
