### ISSUE TITLE
No album data on Spotify Web

### ISSUE THREAD

**Issue by chungkingxpress** [david-sabata/web-scrobbler#1364] opened 2017-07-28 22:54 UTC
All the scrobbles I make from Spotify Web show no album info, all the scrobblings I make show up on my library, but they aren't being added up to the corresponding album. 

![album spotify](https://user-images.githubusercontent.com/30538690/28738961-3385bc2e-73cd-11e7-838e-f6585b8a3de0.png)
(The album name should show up below the name of the band)

I tried scrobbling from Bandcamp and the album info shows up correctly, so I'm thinking it's an issue exclusive to Spotify Web, maybe due to an update or some kind of chage they implemented, since I've also had problems with my ad-blocker failing to block adds on that site.

**Comment by alexesprit** [comment] 2017-07-29 03:18
This is already reported.

There's no a simple way to grab album info from Spotify web player; I plan to fix it by retrieving album info from Last.fm.

Closed as a duplicate of #1320.

**Closed by alexesprit** 2017-07-29 03:18 UTC
