### ISSUE TITLE
Do not scrobble

### ISSUE THREAD

**Issue by sergeychibunin** [david-sabata/web-scrobbler#815] opened 2015-10-19 06:06 UTC
Hello.
A plugin do not scrobble on my win7, google chrome 46.0.2490.71 m.
Please, help.

**Comment by mikdmgo** [comment] 2015-10-19 09:30
Hi,
I have the same issue. Re-authentication is not helping

**Comment by inverse** [comment] 2015-10-19 09:35
Please provide sample URLs, Version of the extension you are using, and if possible a log, please see the wiki for how to capture this.

**Comment by fedorg** [comment] 2015-10-19 13:59
Based on the fact that both submitters are Russian, the issue is most likely fixed in #809.

**Comment by sergeychibunin** [comment] 2015-10-20 04:23
For example, deezer.com.

chrome.storage.local = {"Core":{"appVersion":"1.53"},"LastFM":{"sessionID":"xxxxx71bd222eaa334f7a148c7a7255e","sessionName":"Zloy_yogurt","token":null}}
main.js:220 LastFM: Session ID xxxxx71bd222eaa334f7a148c7a7255e
inject.js:79 -- loaded for the first time, injecting the scripts
inject.js:107 	injecting vendor/jquery-1.6.1.min.js
inject.js:107 	injecting connectors/vk.js
65inject.js:120 -- subsequent ajax navigation, the scripts are already injected
inject.js:79 -- loaded for the first time, injecting the scripts
inject.js:107 	injecting vendor/jquery-1.6.1.min.js
inject.js:107 	injecting connectors/vk.js
13inject.js:120 -- subsequent ajax navigation, the scripts are already injected
scrobbler.js:55 reset called
inject.js:79 -- loaded for the first time, injecting the scripts
inject.js:107 	injecting vendor/jquery-1.6.1.min.js
inject.js:107 	injecting connectors/vk.js
48inject.js:120 -- subsequent ajax navigation, the scripts are already injected
inject.js:79 -- loaded for the first time, injecting the scripts
inject.js:107 	injecting vendor/jquery-1.6.1.min.js
inject.js:107 	injecting connectors/vk.js
2inject.js:120 -- subsequent ajax navigation, the scripts are already injected
inject.js:79 -- loaded for the first time, injecting the scripts
inject.js:107 	injecting vendor/jquery-1.6.1.min.js
inject.js:107 	injecting connectors/vk.js
inject.js:79 -- loaded for the first time, injecting the scripts
inject.js:107 	injecting vendor/jquery-1.6.1.min.js
inject.js:107 	injecting connectors/vk.js
10inject.js:120 -- subsequent ajax navigation, the scripts are already injected
scrobbler.js:55 reset called
3inject.js:120 -- subsequent ajax navigation, the scripts are already injected
scrobbler.js:55 reset called
23inject.js:120 -- subsequent ajax navigation, the scripts are already injected
scrobbler.js:55 reset called
8inject.js:120 -- subsequent ajax navigation, the scripts are already injected
scrobbler.js:55 reset called

**Comment by david-sabata** [comment] 2016-01-02 19:20
If this was caused by the Russian blockage, then it should be resolved by #809.
As this issue is quite old and I'm doing new year's cleaning, I'll close this now. Feel free to re-open or start a new issue if the problem persists.

**Closed by david-sabata** 2016-01-02 19:20 UTC
