### ISSUE TITLE
Edit entries are not memorized

### ISSUE THREAD

**Issue by Mewster** [david-sabata/web-scrobbler#1396] opened 2017-09-08 08:49 UTC
When editing a scrobble, the next time the song gets played it forgets the edit.

### Expected behavior
The scrobble remembers the info from last edit

### Current behavior
The scrobble uses its standard info

### Steps to reproduce (for bugs)
(tried using Spotify Open)
1.  Play a song, edit its info (ex. artists)
2.  Change song
3.  Play the first song again

### Environment
Version: 1.68.1
Browser: Chrome, Versione 60.0.3112.113

**Comment by alexesprit** [comment] 2017-09-08 09:01
This was already reported in #1377 and was fixed in dc77a0f1bd7b8435656eefb01e6886f690eaea16.

Closed as a duplicate of #1377.

**Closed by alexesprit** 2017-09-08 09:01 UTC

**Comment by Mewster** [comment] 2017-09-08 09:09
In which version has been this fixed?

**Comment by alexesprit** [comment] 2017-09-08 11:00
In 2.0.0 (not released yet).

You can install the extension from the master branch, if you don't want to wait until it's released.
