### ISSUE TITLE
Amazon cloud player in Chrome not working...

### ISSUE THREAD

**Issue by Belonogast** [david-sabata/web-scrobbler#847] opened 2015-12-07 16:27 UTC
Hi!

The amazon cloud player scrobbling stopped working. The plugin is not recognizing that a song is playing. I am using german amazon cloud player...

Any ideas?

**Comment by Paszt** [comment] 2015-12-07 21:32
Duplicate of issue #835 which pull request #838 resolves.

**Comment by Zylinderkatze** [comment] 2015-12-10 11:21
It's not working for me either. I get the "is it already playing?"-link in the dialog window. it doesn't look resolved to me..?

**Comment by Belonogast** [comment] 2015-12-10 11:36
I had to change the amazon.js file in my chrome extensions folder, then clear all cache and restart Chrome a few times, but then it worked fine!

**Comment by hilgi** [comment] 2015-12-23 22:10
How do I add the code mentioned above?

**Comment by brarig219** [comment] 2015-12-28 22:12
@Belonogast do you care to elaborate?  @hilgi I'm in the same boat as you and @Zylinderkatze  - It says that it has been fixed, but it's still not working for me.  I know how to find the developer page in the Chrome extensions, but if there's a change I have to make in there, I don't know what that is.  I'm thankful for you all with the knowledge, because coding is beyond me.

**Closed** 2016-01-02 16:09 UTC

**Comment by Zylinderkatze** [comment] 2016-01-10 23:19
@brarig219 it's still not working for me and I assume (maybe wrongly) that it's because I'm on amazon.de not amazon.com? not sure whether the chrome plugin expects / requires a ".com".

This is the path that I play the music from:

https://www.amazon.de/gp/dmusic/cloudplayer/web/

..on which scrobbing is still not working.

**Comment by hilgi** [comment] 2016-01-11 18:58
@Zylinderkatze I just removed the app, shutdown Chrome and rebooted my PC, when I reinstalled it, everything works fine.

**Comment by Zylinderkatze** [comment] 2016-01-27 12:41
@hilgi I did exactly that and it's still not working.
![Song Playing but not Scrobbing](https://cloud.githubusercontent.com/assets/2278160/12613660/68e55ef6-c4fb-11e5-8034-a256223b8d70.png)(Song Playing but not Scrobbing)

..on amazon.de
