### ISSUE TITLE
won't scrobble Google Play Music since last update (1.269.7)

### ISSUE THREAD

**Issue by twerff** [david-sabata/web-scrobbler#604] opened 2015-05-16 12:41 UTC
First of all, great work on the scrobbler app! I love it and have been using it for a year now.
But unfortunately it stopped working with Google Play Music after the last update of Play Music (1.269.7).  The app doesn't recognise that music is playing at all.

Anyone else experiencing this problem?

**Comment by olls** [comment] 2015-05-16 13:21
Duplicate of #602 ?

**Comment by david-sabata** [comment] 2015-05-18 12:52
Yep, dupe. Please check that you have the latest version of the extension.

**Closed by david-sabata** 2015-05-18 12:52 UTC
Labels: 4: DUPLICATE

**Comment by twerff** [comment] 2015-05-18 13:46
Awesome job, thanks dude!
