### ISSUE TITLE
Soundcloud doesn't scrobble

### ISSUE THREAD

**Issue by apaulvs** [david-sabata/web-scrobbler#596] opened 2015-05-12 04:04 UTC
The icon for the Last.fm scrobbler is displayed at the right end of the URL bar whenever I open and use Soundcloud, however, no song is ever scrobbled from the website. :/ I've tried things like disabling and re-enabling soundcloud scrobbling from the settings, and re-authenticating with Last.fm. However, none of these things worked and still nothing is being scrobbled from Soundcloud. Please help.

**Comment by AltarBeastiful** [comment] 2015-05-12 08:41
The issue is known and will get fixed when #573 is merged.

**Comment by EhsanKia** [comment] 2015-05-14 01:15
Sorry for being impatient, but what's the usual timeline on these? It seems like a fairly straight forward change (changing a 16 to 19, and adding fallback). Considering SoundCloud is the 2nd biggest music site and it's been broken for over a month.

**Closed** 2015-05-16 09:16 UTC
Labels: 2: BUG, 3: CONNECTOR

**Comment by joshkaplan** [comment] 2015-06-02 21:52
Soundcloud scrobbling still broken for me
