### ISSUE TITLE
Google Play Music bug?

### ISSUE THREAD

**Issue by G4Zz0L1** [david-sabata/web-scrobbler#664] opened 2015-07-13 08:35 UTC
I've had problems with scrobbling last week, but no visual error, so I've reinstalled everything and the scrobbler worked again. Now it gives some error, but I'm not a js expert, so I can't understand if there's a conflict.
![image](https://cloud.githubusercontent.com/assets/13220636/8645796/cc24e47a-294a-11e5-8956-baa3e38a8722.png)

**Comment by david-sabata** [comment] 2015-07-13 10:45
I see you're getting some errors from another extension "cast sender". Can you try to disable it? 
Also are you using stable Chrome and latest version of the extension?

**Comment by G4Zz0L1** [comment] 2015-07-13 15:40
I'm using the dev channel. I can't disable it, because it's the internal control of chrome for chromecast, if google doesn't lie to me.

**Comment by inverse** [comment] 2015-07-13 20:54
Are you chromecasting google music whilst this issue occurs?

**Comment by G4Zz0L1** [comment] 2015-07-14 08:06
No, that cast-sender bug is there anyway.

http://stackoverflow.com/questions/24490323/google-chrome-cast-sender-error-if-chrome-cast-extension-is-not-installed-or-usi

**Comment by david-sabata** [comment] 2015-07-14 08:08
In that case I need you to check if the issue is present in beta or stable Chrome channel.

**Comment by G4Zz0L1** [comment] 2015-07-14 08:13
I'll try on another pc, when i get the chance, and report asap, but it should work if I'm not wrong. I've only linux at home, and it works ok on chromium-unstable.

**Comment by code-for-coffee** [comment] 2015-07-16 03:02
Getting the same error on Chrome Canary version 46.0.2456.0 canary (64-bit). 

```javascript
chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js Failed to load resource: net::ERR_FAILED
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm/cast_sender.js Failed to load resource: net::ERR_FAILED
polymer_srcs.js:14 Calling Element.createShadowRoot() for an element which already hosts a shadow root is deprecated. See https://www.chromestatus.com/features/4668884095336448 for more details.
polymer_srcs.js:31 ::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
chrome-extension://hfaagokkkhdbgiakmmlclaapfelnkoah/cast_sender.js Failed to load resource: net::ERR_FAILED
chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js Failed to load resource: net::ERR_FAILED
chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js Failed to load resource: net::ERR_FAILED
chrome-extension://eojlgccfgnjlphjnlopmadngcgmmdgpk/cast_sender.js Failed to load resource: net::ERR_FAILED
/Users/jamest/Library/Application%20Support/Google/Chrome%20Canary/Profile%…ensions/hhinaapppaileiechjoiifaancjggfjm/1.49_0/core/content/starter.js:35 Web Scrobbler: Setting up observer
```

**Comment by david-sabata** [comment] 2015-07-16 10:38
@code-for-coffee we already know the error is on Canary. But that's not a supported Chrome channel. If beta or stable is affected too, I'll look into it.

**Comment by hambro** [comment] 2015-07-25 14:10
I have the same error in stable version 44.0.2403.89 .

**Comment by womke** [comment] 2015-08-03 08:47
I have the same error in stable Version 44.0.2403.125

**Comment by duskox** [comment] 2015-08-18 21:57
I have same error in Version 44.0.2403.155 (64-bit)
<img width="319" alt="screen shot 2015-08-18 at 23 57 28" src="https://cloud.githubusercontent.com/assets/792923/9343865/edf746d4-4604-11e5-9c8b-feca86c10d96.png">

**Comment by david-sabata** [comment] 2015-08-19 05:36
@duskox Can you please check where the `default.js` file is from? Doesn't seem to be ours

**Comment by duskox** [comment] 2015-08-19 09:17
default.js is from Codota, as it is mentioning something about syntax highlighting. I disabled it and the errors are gone.

I temporarily fixed it yesterday, I had to install "Google Cast" Chrome extension, then I restarted Chrome, reauthorised with Last.fm and then again restarted Chrome, then it worked, until today. It is not scrobbling again.

Error with Codota:
<img width="1431" alt="screen shot 2015-08-19 at 10 57 59" src="https://cloud.githubusercontent.com/assets/792923/9352683/78b0de44-4663-11e5-8516-b0dad073f835.png">

And this without error, after I disabled Codota:
<img width="1437" alt="screen shot 2015-08-19 at 11 15 01" src="https://cloud.githubusercontent.com/assets/792923/9352707/92389f0a-4663-11e5-9b7b-cc5d31a5a39e.png">

Now I tried the same thing, killed Chrome, restarted and reauthorised but no scrobbling. If you have any other ideas what to check and how I can help let me know.
Cheers!

**Comment by inverse** [comment] 2015-08-19 10:25
Seems odd. Are we having weird interactions with other extensions injecting scripts into the pages?

**Comment by david-sabata** [comment] 2015-08-19 10:50
No. At least not intentionally.

Can some of you guys who are experiencing this issue try to disable all other extensions and see if the scrobbling works?

**Comment by hambro** [comment] 2015-08-19 11:03
No change at all. "Web Scrobbler: Setting up observer" is the last entry.

**Comment by hambro** [comment] 2015-08-19 11:10
Not sure what fixed it, but reauthenticated now and it works. Enabled all
extensions and it still works.
Funky bug

**Comment by duskox** [comment] 2015-08-19 11:15
No change for me, tried also to reauth (did not ask me for authorisation though) and restart Chrome, but no scrobbling. Maybe that is the thing? Many times I tried Re-Authorise button but I never got asked to authorise it on Last.fm page.

**Comment by david-sabata** [comment] 2015-08-19 11:17
@duskox Can you post what's in console on options page, when you click the reauth button and nothing seems to happen?

**Comment by duskox** [comment] 2015-08-19 11:20
Here it is.
<img width="1440" alt="screen shot 2015-08-19 at 13 20 20" src="https://cloud.githubusercontent.com/assets/792923/9354981/1678aa4c-4675-11e5-83f7-53b5d313b4c3.png">

**Comment by janbaykara** [comment] 2015-08-19 12:05
Bear in mind the Last.fm beta site just went live, and temporarily disabled API authorisation...

**Comment by duskox** [comment] 2015-08-19 12:11
I know but that was happening before also, I have had this problem for a really long time but never reported it.

**Comment by pvj** [comment] 2015-08-25 08:26
Having the same issue, newly installed machine, newly installed, stable, up-to-date Chrome. It's the first extension I installed (props for all the work guys!) and I'm seeing the same issues as listed above. 

On **Google Music** (using the link: https://play.google.com/music/listen#/now) it's just that there's nothing after this line `Web Scrobbler: Setting up observer`

On **YouTube** there's no output in the console at all.

**Bandcamp** is the weirdest, I'm seeing this line: `Web Scrobbler: Connector.playerSelector is empty. The current connector is expected to manually detect state changes`.

**Comment by Paszt** [comment] 2015-08-25 12:40
@pvj: If no websites are working you probably have a different issue than the one being discussed here.  
There's an issue with authorizing the application which #718 should fix.  You can debug and see if the errors are the same as above or related to authorizing. I've recently done a full reinstall and faced the same issue.
https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension

Bandcamp is using a non-default method for detection and the message is expected and just a warning.

**Comment by pvj** [comment] 2015-08-25 13:58
@Paszt thanks for the clarification and the links.

**Comment by duskox** [comment] 2015-08-25 14:02
Thanks also, through debugging I found that I am not authorised somehow, I get 403 error.
<img width="1436" alt="screen shot 2015-08-25 at 14 50 04" src="https://cloud.githubusercontent.com/assets/792923/9468552/84720a1c-4b42-11e5-9067-ca8c428f73d4.png">
<img width="1440" alt="screen shot 2015-08-25 at 14 50 33" src="https://cloud.githubusercontent.com/assets/792923/9468553/84778082-4b42-11e5-920f-9ff1e9b67e74.png">

Maybe after they allow authorising on Last.fm it will work.

**Comment by pvj** [comment] 2015-08-25 14:13
@Paszt Confirming that reauth worked, thanks again and sorry for offtopic.

**Comment by alexesprit** [comment] 2017-01-16 14:57
Closed as outdated.

**Closed by alexesprit** 2017-01-16 14:57 UTC
Labels: 1: NEEDS CONFIRM, 2: BUG, 3: CONNECTOR, 4: OUTDATED
