### ISSUE TITLE
Chrome extension not working with Pandora.

### ISSUE THREAD

**Issue by MRmarkMAN** [david-sabata/web-scrobbler#1342] opened 2017-06-23 04:33 UTC
The extension will no longer scrobble my Pandora. A few days ago it was working fine and now it just will not work. I disabled and re-enabled the connector, logged out and back in to Pandora, and re-verified my account with last.fm. The extension will work fine on other sites like Spotify however. I'm stumped and not sure if the issue is on my end or not and so far I can't find anything to make me think that it is.

**Comment by ducker3** [comment] 2017-06-23 16:00
I've been having this same issue for a number of days, after checking the forum I attempted to delete the extension, reboot, and then re-download/add it and sync it up to all my accounts - but still failing to work with Pandora.

**Comment by paladzin** [comment] 2017-06-23 19:55
Same here

**Comment by LxNix** [comment] 2017-06-24 03:08
me too

**Comment by alexesprit** [comment] 2017-06-24 06:25
Closed as a duplicate of #1339.

**Closed by alexesprit** 2017-06-24 06:25 UTC
Labels: 3: CONNECTOR
