### ISSUE TITLE
YouTube scrobbles as youtube.com/devicesupport

### ISSUE THREAD

**Issue by maxdaniel98** [david-sabata/web-scrobbler#593] opened 2015-05-08 14:52 UTC
When using YouTube, web-scrobbler scrobbles as youtube.com/devicesupport.

**Comment by inverse** [comment] 2015-05-08 14:57
dupe of #590

**Comment by MansourMans** [comment] 2015-05-10 02:39
On youtube it scrobbles track as  <youtube.com/devicesupport> and artist as <http>
![snap](https://cloud.githubusercontent.com/assets/12377342/7552839/df54f7c0-f6d6-11e4-9aa5-cbdb12782fa3.JPG)

**Closed** 2015-05-11 06:14 UTC
Labels: 4: DUPLICATE
