### ISSUE TITLE
auto-closes and warns no scrobbing  Firefox ESR 52.3.0 (32-bits)  :(

### ISSUE THREAD

**Issue by ago2180** [david-sabata/web-scrobbler#1374] opened 2017-08-17 02:31 UTC
### Steps to reproduce (for bugs)

1.  
2.  
3.  

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser name and version:

**Comment by alexesprit** [comment] 2017-08-17 15:01
Can you describe the issue clearly?

**Comment by alexesprit** [comment] 2017-09-17 09:00
Closed as outdated.

**Comment by LaHaine** [comment] 2017-09-29 09:25
I'd like to reopen this. The new version 2.0.1 of the scrobbler doesn't work on Firefox ESR 52.3.0 (64 bit, Linux in my case). You can authenticate, but the list of supported websites in the options dialog is empty.

**Comment by LaHaine** [comment] 2017-09-29 09:30
I can confirm that a downgrade to 1.68.1 helped, so there was a change in 2.0 that was incompatible with Firefox ESR 52.3.0.

**Comment by alexesprit** [comment] 2017-09-29 15:35
I noticed a similar issue on beta version of Firefox. Will try to reproduce it on ESR.

**Comment by alexesprit** [comment] 2017-09-30 13:40
ESR does not include enabled sync storage by default. That's why the extension doesn't work in ESR properly.

Currently I have no solution in code that would fix the issue. As a workaround I can suggest to enable sync storage in `about:config`:
```
webextensions.storage.sync.enabled: true
```

**Comment by kfinelli** [comment] 2017-10-05 18:56
Thanks @alexesprit, I was having the same issue and this solved it.  Perhaps a pop-up warning could be displayed if this setting is detected to be off?

**Comment by alexesprit** [comment] 2017-10-07 15:30
@kfinelli I'm not sure if it's possible to implement since WebExtensions have no access to Firefox settings.

**Closed** 2017-10-27 15:37 UTC
Labels: 4: INCONCLUSIVE
