### ISSUE TITLE
Suggestions: Add A Universal Connector

### ISSUE THREAD

**Issue by AhmedKamal20** [david-sabata/web-scrobbler#1300] opened 2017-05-02 16:37 UTC
Can we Add a Connector that will work for other websites , that have a predefined selectors 
So , me as a website maker can add this selectors with song's data to enable web-scrobbler users to use it 

And even more , can we add an option for the users to add custom selector for a custom connector 
to be able to use the ext. with any website they want that is't listed here ?

**Comment by alexesprit** [comment] 2017-05-02 16:59
I think it's easier to write a connector and include it to the extension. I believe people who know CSS are able to write a couple of lines of connector code.

I'm also not sure if this complex feature will be useful for a lot of people.

**Comment by AhmedKamal20** [comment] 2017-05-02 17:17
ok , i can write a connector, but will you accept a not-popular site (~ 15 users per day !), if this is the case , i will do it  of course.

**Comment by alexesprit** [comment] 2017-05-02 17:21
@AhmedKamal20 that's ok, feel free to create a PR for a connector.

**Comment by inverse** [comment] 2017-05-02 18:05
I think having a universal connector (connector "builder") would be a lot of work. I think the this extension has come a long was to generalise the scrobbling functionality and developer usability when building new extensions. 

Perhaps we could provide richer documentation but I believe the core scrobbler class is pretty well self documented for developers to build against. We could perhaps add proper comments to a few of our connectors that touch some of the core functionality. @alexesprit what do you think?

@AhmedKamal20 as for your site in question - building for a new site no matter how small the traffic is we will accept.

**Comment by alexesprit** [comment] 2017-06-12 12:14
I'm closing this as a duplicate of #454. As previously said v2 format is pretty easy, and working connectors are always welcome.

**Closed by alexesprit** 2017-06-12 12:14 UTC
Labels: 1: DISCUSSION
