### ISSUE TITLE
Scrobbler doesn't grab the Spotify album info

### ISSUE THREAD

**Issue by Besatnias** [david-sabata/web-scrobbler#1395] opened 2017-09-07 12:35 UTC
When I'm scrobbling on Spotify (Open player, Chrome extension), I'd expect the extension to grab the album metadata of the song I'm playing. However, it only grabs the song and artist, while the album field is left blank. I'd have to fill it with each song, but that's too much work for someone who listens to more than 300 songs a day while multitasking. Is it possible to resolve this?

![image](https://user-images.githubusercontent.com/23301025/30163569-6e3c564e-93a7-11e7-8307-ef79f0ff9a7c.png)

![image](https://user-images.githubusercontent.com/23301025/30163601-7f0c77d8-93a7-11e7-95bf-d3a6efb9a228.png)

**Comment by nickeatingpizza** [comment] 2017-09-07 15:50
I second that. Been having the same problem for a while now and can't really figure out wether it 
if it comes from the last.fm side or the web-scrobbler (I use the firefox version btw)
Just now I have tried playing the same song both on web open.spotify and on the desktop (windows) app. As you can see here the first one did not scrobble album, but the second did.

![pai2](https://user-images.githubusercontent.com/28931163/30171706-fadd35dc-93f2-11e7-8a0a-3db77190e2a6.png)

![pai3](https://user-images.githubusercontent.com/28931163/30171808-3fb01d82-93f3-11e7-8600-f40c8e7ecf7c.PNG)

However this is not always the case, as this album I played yesterday from the Web app was scrobbled correctly even though the web-scrobbler left the album field blank...

[https://www.last.fm/user/nico_sasshi/library/music/Cloud+Control/Zone?date_preset=LAST_7_DAYS](url)
![pai4](https://user-images.githubusercontent.com/28931163/30172044-eeaa12e8-93f3-11e7-87cf-2cc2b3d19fa1.png)

On the other hand, all LCD Soundsystem new record scrobblings I've been doing from open.spotify are missing the album, so maybe it has just something to do with new releases that are not yet present in last.fm database, but then again Spotify desktop app (or playing tagged mp3 files from Winamp ) don't seem to be affected by the problem.  
That said, album stats on last.fm are _definitely_ skewed by this and I a fix would be appreciated.

**Comment by alexesprit** [comment] 2017-09-08 09:04
There's no simple way to get album info from Spotify Web Player. This issue is partially resolved in c7b5bc84105bd894785f5f44b492678d3bb89d19; the extension will get album info using Last.fm API.

**Comment by alexesprit** [comment] 2017-09-12 17:02
Closed as a duplicate of #1320.

**Closed** 2017-09-12 17:01 UTC
Labels: 2: BUG, 3: CONNECTOR
