### ISSUE TITLE
YouTube has disabled their old data API, rendering the YouTube connector nonfunctional

### ISSUE THREAD

**Issue by soliloquial** [david-sabata/web-scrobbler#590] opened 2015-05-06 20:47 UTC
YouTube is now returning the following for all data API requests from the old API:

    {"version":"1.0","encoding":"UTF-8","entry":{"xmlns":"http://www.w3.org/2005/Atom","xmlns$yt":"http://gdata.youtube.com/schemas/2007","xmlns$media":"http://search.yahoo.com/mrss/","id":{"$t":"http://gdata.youtube.com/feeds/api/videos/UKY3scPIMd8"},"published":{"$t":"2015-04-17T15:23:22.000Z"},"updated":{"$t":"2015-05-06T20:20:34.000Z"},"category":[{"scheme":"http://schemas.google.com/g/2005#kind","term":"http://gdata.youtube.com/schemas/2007#video"},{"scheme":"http://gdata.youtube.com/schemas/2007/categories.cat","term":"Howto","label":"Howto & Style"}],"title":{"$t":"https://youtube.com/devicesupport","type":"text"},"content":{"$t":"https://youtube.com/devicesupport\nhttp://m.youtube.com","type":"text"},"link":[{"rel":"alternate","type":"text/html","href":"https://www.youtube.com/watch?v=UKY3scPIMd8&feature=youtube_gdata"},{"rel":"http://gdata.youtube.com/schemas/2007#video.related","type":"application/atom+xml","href":"https://gdata.youtube.com/feeds/api/videos/UKY3scPIMd8/related"},{"rel":"http://gdata.youtube.com/schemas/2007#mobile","type":"text/html","href":"https://m.youtube.com/details?v=UKY3scPIMd8"},{"rel":"self","type":"application/atom+xml","href":"https://gdata.youtube.com/feeds/api/videos/UKY3scPIMd8"}],"author":[{"name":{"$t":"YouTube Help"},"uri":{"$t":"https://gdata.youtube.com/feeds/api/users/YouTubeHelp"}}],"yt$hd":{},"media$group":{"media$category":[{"$t":"Howto","label":"Howto & Style","scheme":"http://gdata.youtube.com/schemas/2007/categories.cat"}],"media$content":[{"url":"https://www.youtube.com/v/UKY3scPIMd8?version=3&f=videos&app=youtube_gdata","type":"application/x-shockwave-flash","medium":"video","isDefault":"true","expression":"full","duration":236,"yt$format":5},{"url":"rtsp://r1---sn-p5qlsu76.c.youtube.com/CiILENy73wIaGQnfMcjDsTemUBMYDSANFEgGUgZ2aWRlb3MM/0/0/0/video.3gp","type":"video/3gpp","medium":"video","expression":"full","duration":236,"yt$format":1},{"url":"rtsp://r1---sn-p5qlsu76.c.youtube.com/CiILENy73wIaGQnfMcjDsTemUBMYESARFEgGUgZ2aWRlb3MM/0/0/0/video.3gp","type":"video/3gpp","medium":"video","expression":"full","duration":236,"yt$format":6}],"media$description":{"$t":"https://youtube.com/devicesupport\nhttp://m.youtube.com","type":"plain"},"media$keywords":{},"media$player":[{"url":"https://www.youtube.com/watch?v=UKY3scPIMd8&feature=youtube_gdata_player"}],"media$thumbnail":[{"url":"https://i.ytimg.com/vi/UKY3scPIMd8/0.jpg","height":360,"width":480,"time":"00:01:58"},{"url":"https://i.ytimg.com/vi/UKY3scPIMd8/1.jpg","height":90,"width":120,"time":"00:00:59"},{"url":"https://i.ytimg.com/vi/UKY3scPIMd8/2.jpg","height":90,"width":120,"time":"00:01:58"},{"url":"https://i.ytimg.com/vi/UKY3scPIMd8/3.jpg","height":90,"width":120,"time":"00:02:57"}],"media$title":{"$t":"https://youtube.com/devicesupport","type":"plain"},"yt$duration":{"seconds":"236"}},"yt$statistics":{"favoriteCount":"0","viewCount":"4674155"}}}

Clearly, this does not contain the desired information, and as a result all YouTube scrobbles are gibberish. The correct API link is now:

`https://www.googleapis.com/youtube/v3/videos?id=VIDEO_ID&key=YOUR_API_KEY&part=snippet,contentDetails,statistics,status`

However, this requires an API key.

Solution without an API key would be to just use track_dom/artist_dom for now instead of info.entry.title.$t.

**Comment by Aracki** [comment] 2015-05-06 23:49
it returns https – youtube.com/devicesupport all the time

**Comment by dotWee** [comment] 2015-05-07 13:06
Same here, Constant 'https – youtube.com/devicesupport' return.
![Imgur](http://i.imgur.com/glkQ9Bd.png)

**Comment by aemxdp** [comment] 2015-05-07 15:46
This stuff is becoming popular: http://www.last.fm/music/https
![image](https://cloud.githubusercontent.com/assets/10787043/7519388/360f620c-f4e9-11e4-997c-457ba55649c8.png)

**Comment by kytwb** [comment] 2015-05-07 16:22
:+1:

**Comment by evinugur** [comment] 2015-05-07 16:41
relevant thread on last.fm http://www.last.fm/music/https/_/youtube.com%2Fdevicesupport

Since this bug still scrobbles (just the wrong thing), I think that a version should be deployed with the YouTube feature disabled until a fix is rolled out. This way people who use the program for other services don't get their last.fm cluttered with the false-scrobbles when browsing/watching YouTube. 

Just my $0.02.

**Comment by dotWee** [comment] 2015-05-07 16:46
https? I love that band!

![Imgur](http://i.imgur.com/rjpTdhU.png)

**Comment by XenHat** [comment] 2015-05-07 18:52
Yep, I'm having this problem as well. I hope things can be sorted out :smile:

**Comment by colwellkr** [comment] 2015-05-08 17:59
If having a bunch of https scrobbles in your history bothers you, you can turn it off for youtube in the settings. I do hope the issue gets resolved soon though ^^

**Comment by socketubs** [comment] 2015-05-09 09:36
Same bug here.
https is such a great band.

**Comment by Daniel15** [comment] 2015-05-11 05:04
LOL, 241,178 scrobbles for that "track". Nice.

**Comment by kytwb** [comment] 2015-05-11 10:40
Seems to be fixed for me.

**Comment by david-sabata** [comment] 2015-05-11 10:46
Resolved by 84933bd

**Closed by david-sabata** 2015-05-11 10:46 UTC
Labels: 2: BUG, 3: CONNECTOR

**Comment by bk138** [comment] 2015-05-11 10:50
Confirmed, youtube scrobbling is working again!

**Comment by llisama** [comment] 2015-05-12 03:16
confirmed? 
it doesn't seem to be working for me. i never had the https thing happening. but just nothing has ben happening at all for a few days now. shiiieeeeettt

**Comment by david-sabata** [comment] 2015-05-12 07:22
@bk138 are you sure you already have the 1.46 update?

**Comment by aemxdp** [comment] 2015-05-12 10:22
@david-sabata Hm, I've checked the latest version from chrome store and it doesn't seem to work for me.

**Comment by bk138** [comment] 2015-05-12 11:34
@david-sabata I said it works well ;-)

**Comment by aemxdp** [comment] 2015-05-12 12:36
@david-sabata Ah, it doesn't work only when "Scrobble only Music category" is on.
