### ISSUE TITLE
Hi guys

### ISSUE THREAD

**Issue by pink999** [david-sabata/web-scrobbler#700] opened 2015-08-20 05:06 UTC
Youtube is not working for lost fm (omg it looks so awful), bandcamp works, Soundcloud, seem just youtube issue, I didn't see it posted so "post"

not sucking up when I  say you geeks are the best, maybe a little, I don't know if this has to do with change in format,, because spot uses youtube also - correct?

well this is a heads up that mini scrobbler works okay, but if you listen to unusal music as I tend to you have to write most of the tracks in - so thanks for the voodo you do :)

**Comment by pink999** [comment] 2015-08-23 08:18
Bad time - eh............ (reading from below)

Issue, people are complaining like crazy, but won’t tell you peeps’ (might be the name-calling?), you get that error now, and every play “check status, check with the people who are?”  all green lights, all working?

Tampermonkey works, and it seems all else is working but one play is producing 3,4,5 scrobbles of same track at once (biggest complaint of users) the media player(s) are not tracking from iTunes, problems off and on with WMP --- but that has been an issue for a while and you don’t have anything to do with that – right?

So that is it folks - you tube videos no go and multi tracks per play I am not sure if that is an issue out the media players? people complain, but don't say what is being used or where from.

Thx~~ FAST! Spell Abracadabra ~~ *poof*

**Comment by david-sabata** [comment] 2015-08-23 11:59
Duplicate of #698

**Closed by david-sabata** 2015-08-23 11:59 UTC
Labels: 4: DUPLICATE
