### ISSUE TITLE
163 music doesn't scrobble now.

### ISSUE THREAD

**Issue by bluemelodypp** [david-sabata/web-scrobbler#1303] opened 2017-05-04 16:27 UTC
http://music.163.com/#
this website can‘t be scrobbled now

**Comment by alexesprit** [comment] 2017-05-04 18:43
Duplicate of #1284.

**Closed** 2017-05-04 18:43 UTC
Labels: 4: DUPLICATE

**Comment by bluemelodypp** [comment] 2017-05-05 14:50
I reinstall the plugin but still not working.

**Comment by alexesprit** [comment] 2017-05-05 14:54
It shouldn't work, because new version is not released. The issue is already reported and is fixed; that's why I closed it.

**Comment by bluemelodypp** [comment] 2017-05-05 14:58
Thanks!!! 
BTW when will it release?
