### ISSUE TITLE
New Spotify Web Player doesn't scrobble

### ISSUE THREAD

**Issue by fabionapodano** [david-sabata/web-scrobbler#1277] opened 2017-04-11 06:43 UTC
### Expected Behavior
Spotify recently changed their web player, removing last.fm support. At its first incarnation (some weeks ago), this extension was working and was the only working solution known to me. Then, the old player was back. Since some days, the new web player is online again, but this extension is not working anymore.

### Current Behavior
scrobbling doesn't work. already tried to reauthorize the extension.

**Comment by alexesprit** [comment] 2017-04-11 06:46
Duplicate of #1270.

This issue is already fixed. The new version will be available in Chrome Web Store soon.

**Closed by alexesprit** 2017-04-11 06:46 UTC
