### ISSUE TITLE
Long tracks are sometimes scrobbled twice

### ISSUE THREAD

**Issue by marsjaninzmarsa** [david-sabata/web-scrobbler#1426] opened 2017-10-08 04:55 UTC
Reported by @hans-juergen in https://github.com/david-sabata/web-scrobbler/issues/1418#issuecomment-334977280:
> Using the new version of the extension I also noticed that sometimes scrobbles are duplicated for no apparent reason. I tried to find out why, but can only guess: maybe this only happens with long tracks over 8 minutes, and/or it happens when another track cannot be scrobbled at all, so the duplicate would be some kind of a placeholder for the missing scrobble?

> Everything OK so far with scrobbling Release Radar. Now I am playing my Discover Weekly playlist, and the same problem came up: The second track of that playlist "Little Boy Blues" by Triumph did not scrobble at all, and the third track "Hey Joe - Live" by Gary Moore which is 9:35 min. long was duplicated with a difference in scrobbled time of 4 minutes. You might know that this is the maximum time after a track gets scrobbled independent from its real length. I did not delete these duplicates from my library, so you can check it yourself in my recent tracks list.

**Comment by alexesprit** [comment] 2017-10-08 04:59
This could happen because of repeat detection.

**Comment by alexesprit** [comment] 2017-10-08 05:02
@hans-juergen I've just remembered I fixed a bug recently related to repeat detection. Could you check the extension from the master branch and reproduce the issue again?

**Comment by hans-juergen** [comment] 2017-10-08 05:05
I would if you link me to a description how to do this. ;-) Probably I have to download some ZIP file and import it in Opera in expert mode or something like this?

**Comment by alexesprit** [comment] 2017-10-08 05:07
Right. [Here](https://github.com/david-sabata/web-scrobbler#unpacked-extension) is an instruction and [here](https://github.com/david-sabata/web-scrobbler/archive/master.zip) is a zipball.

**Comment by hans-juergen** [comment] 2017-10-08 05:14
I already tried that with the unpacked web-scrobbler-master.zip file and got an error message in Opera that the "manifest" file would be missing. When I check its folder, I can see a "manifest.json" file though. Do I have to rename it perhaps?

**Comment by alexesprit** [comment] 2017-10-08 05:19
Hmm, Opera should not show the error message. I use unpacked extension on Opera and everything works fine for me. `manifest.json` is a correct name for manifest file.

**Comment by hans-juergen** [comment] 2017-10-08 05:28
My fault: I chose the upper folder in the zip file when importing which has no files. You have to import from the actual nested folder with all files in it.

OK, now Opera shows version 2.0.0 for the extension with an additional error message in orange. Should I try to scrobble with it nevertheless?

**Comment by alexesprit** [comment] 2017-10-08 05:29
> OK, now Opera shows version 2.0.0 for the extension with an additional error message in orange. Should I try to scrobble with it nevertheless?

No, you should authenticate before.

**Comment by hans-juergen** [comment] 2017-10-08 05:40
OK, now I am scrobbling "Hey Joe - Live" again with a 9:35 min track length, see [my Last.fm profile](https://www.last.fm/user/hjbardenhagen).

**Comment by alexesprit** [comment] 2017-10-08 05:47
I've just scrobbled a track with 8:06 min length, have no dups.

**Comment by hans-juergen** [comment] 2017-10-08 05:52
Right, "Comfortably numb - live version" by Roger Waters is 8:03 long, and it also scrobbled once with version 2.0.1 before. So maybe the critical length is somewhere above that.

**Comment by hans-juergen** [comment] 2017-10-08 07:56
Last duplicate from that playlist is Iron Maiden - Rime of the Ancient Mariner, but Last.fm knows the related "Powerslave" album apparently, although Spotify calls it "Powerslave (1998 Remastered Edition)".

**Comment by alexesprit** [comment] 2017-10-08 08:06
@hans-juergen so, the extension from master branch makes duplicates too, right?

**Comment by hans-juergen** [comment] 2017-10-08 08:29
No, that one is OK, I called it 2.0.0 in my report.

**Comment by alexesprit** [comment] 2017-10-18 03:57
Closing this as resolved.

**Closed by alexesprit** 2017-10-18 03:57 UTC
Labels: 2: BUG, 3: CORE
