### ISSUE TITLE
Multiple notifications on Pandora

### ISSUE THREAD

**Issue by gsingh93** [david-sabata/web-scrobbler#278] opened 2013-12-08 20:44 UTC
I get around two notifications when a new song starts and then I get one or two more throughout the song. I should only be getting a notification when the song starts.

**Comment by inverse** [comment] 2016-08-13 16:38
Closing as we have v2 version of this scrobbler. Please report back if the problem is still apparent.

**Closed by inverse** 2016-08-13 16:38 UTC
Labels: 1: NEEDS CONFIRM, 2: BUG, 3: CONNECTOR
