### ISSUE TITLE
https://open.spotify.com/

### ISSUE THREAD

**Issue by 4m1lt0n** [david-sabata/web-scrobbler#1271] opened 2017-04-03 00:29 UTC
### Steps to Reproduce (for bugs)

1.  
2.  
3.  

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser Name and version:
Chrome, v. 57.0.2987.133

**Comment by alexesprit** [comment] 2017-04-03 03:56
Looks like it duplicate of #1270 or #1269.

**Closed by alexesprit** 2017-04-03 03:56 UTC
