### ISSUE TITLE
soundcloud on firefox

### ISSUE THREAD

**Issue by arnaud-thouverey** [david-sabata/web-scrobbler#1399] opened 2017-09-13 14:47 UTC
Hello,
I wonder if i'm the only one having this problem. When I play songs in soundcloud, I get the add-on notifications but songs are not reported in my last.fm profile.
I'm using last version of firefox (55) but I believe it's an old problem.
Cheers

**Comment by alexesprit** [comment] 2017-09-13 15:53
Can't reproduce the issue. Have you any additional info?

Is it happening with Soundcloud only?

**Comment by bykidi** [comment] 2017-09-13 20:06
I used to have some weird problems during firefox developer edition versions, like b7-b11. but now everything is working fine

**Comment by alexesprit** [comment] 2017-10-29 07:05
Closed as outdated.

**Closed by alexesprit** 2017-10-29 07:05 UTC
Labels: 4: INCONCLUSIVE
