### ISSUE TITLE
i have to constantly reconnect to last.fm

### ISSUE THREAD

**Issue by linussblanket** [david-sabata/web-scrobbler#990] opened 2016-06-25 04:54 UTC
seems  that every time i start the browser, a pop-up asks me to authenticate the application

**Comment by ssebbass** [comment] 2016-06-25 05:42
Same issue.

Ubuntu Xenial
Google Chrome 51.0.2704.106-1

**Comment by ifthenelse** [comment] 2016-06-30 22:24
Isn't it a duplicate of #981 ?

**Comment by ssebbass** [comment] 2016-07-01 11:31
Yes, could be a duplicate...

About the issue, it seems to drop access on one browser (for instance my home pc), when I login in my other computer.
I have stopped login in in all except for one computer, and then it stops asking for access to last.fm.

**Comment by david-sabata** [comment] 2016-08-07 20:27
Closed in favor of #981

**Closed by david-sabata** 2016-08-07 20:27 UTC
Labels: 4: DUPLICATE
