### ISSUE TITLE
Have to tag every song of my playlist even if I have already tagged it manually

### ISSUE THREAD

**Issue by remi-douteaud** [david-sabata/web-scrobbler#1245] opened 2017-02-21 09:27 UTC
### Expected Behavior
When playing again the same video, should recognize it and scrobble it again.

### Current Behavior
I'm playing a huge playlist of korean song (so the automatic recognition is a mess). I tagged them every time a new one was played but realized even the ones I've already tagged are not recognized after.

### Possible Solution
* Save previously scrobbled songs based on song ID.
* Being able to favourite songs / playlists and save them based on ID to automatically scrobble them.

### Steps to Reproduce (for bugs)
1. Listen to this playlist : https://www.youtube.com/watch?v=LR0pKtiaBJ0&index=5&list=PL7-lpefz7vzkCDL3-xRH5emCIg5XDJLQM
2. Play a song, tag it manually.
3. Change to another one.
4. Play again the first one. It's not detected despited having been tagged.

### Context
I don't want to spend my day tagging same songs again and again.

### Environment
* Version used: 1.61.0
* Browser Name and version: Chrome Version 56.0.2924.87 (64-bit)

**Comment by inverse** [comment] 2017-02-21 09:57
Duplicate of #291

**Closed** 2017-02-21 10:23 UTC
Labels: 2: FEATURE, 3: CORE

**Comment by alexesprit** [comment] 2017-02-21 15:35
No, it's not a duplicate of #291, but such feature is already implemented and will be available in the next release.
