### ISSUE TITLE
Spotify

### ISSUE THREAD

**Issue by HZNetworks** [david-sabata/web-scrobbler#1217] opened 2017-01-08 17:19 UTC
Spotify web player doesn't work with it. It just says Start by playing some music. Although spotify allows last.fm to be linked directly to the account it still is a issue

**Comment by alexesprit** [comment] 2017-01-08 17:22
Can't reproduce it, the extension works with Spotify for me:
![image](https://cloud.githubusercontent.com/assets/1119267/21751908/14465f16-d5e0-11e6-81ca-27b50216e5f7.png)

Have you any additional information?

**Comment by alexesprit** [comment] 2017-01-08 17:45
@HZNetworks could you please check possible fix for Spotify? https://github.com/alexesprit/web-scrobbler/archive/spotify-test.zip

**Comment by ftkftw** [comment] 2017-01-09 22:51
I've been having this issue for a while now. The built-in Spotify lastfm scrobbler isn't any better.

I suspect the problem lies with the Spotify UI itself. Often I find that the web player UI hasn't updated the song name even though the audio stream has already moved on to the next song.

I'm using AdBlock and blocked all third-party cookies and site data, and am using it in Incognito mode. Don't know if any of these makes a difference.

**Comment by alexesprit** [comment] 2017-01-10 02:57
@ftkftw what about fix I posted above? Have you tried to install it?

**Comment by ftkftw** [comment] 2017-01-10 18:52
@alexesprit Did that, but now I'm having no luck re-authenticating the new extension with last.fm

**Comment by alexesprit** [comment] 2017-01-10 18:53
@ftkftw any details?

**Comment by ftkftw** [comment] 2017-01-10 19:00
@alexesprit Clicking on the Re-authenticate button doesn't result in any visual changes aside from the button color changing. I checked the extension's background page/console view and don't see anything relating to the button click. However, if I start playing a song on Bandcamp the console says something about unable to exchange token for session (paraphrasing here).

I've encountered this issue before; reauthenticate doesn't seem to do anything. Is this a known problem?

**Comment by alexesprit** [comment] 2017-01-10 19:11
@ftkftw that's sort of known problem, but there's no steps to reproduce it. I suppose it's a problem on the Last.fm side, but I'm not sure. I tried to resolve this by adding an error notification if auth cannot be performed: https://github.com/alexesprit/web-scrobbler/archive/async-auth.zip. It would be great if you check that too.

> I checked the extension's background page/console view and don't see anything relating to the button click

That information should be available in the options page console log. You can open it by Ctrl-Shift-I when you're on the options page.

Anyway, you still can check Spotify scrobbling, the extension should recognize a song even if it's not authorized (it might show you an error message, but that means the song is recognized).

**Comment by ftkftw** [comment] 2017-01-10 19:45
@alexesprit You are right, the options page console shows something. Network trace shows the gettoken request was successful. However, the extension never prompted me to login to my lastfm account after installing it, so I don't know how useful it is to reauthenticate the extension, if reauthenticating doesn't seem to involve user authentication.

From what I remembered, with the published version of the extension, the extension icon is green (song recognized), but the recognized song is an older song than the one that is currently playing. This matches up with what I said of the Spotify UI earlier, about how the Spotify UI itself is not up-to-date with respect to the currently playing song (I assume the web scrobbler is reading song data from the content of the HTML itself). Often I've noticed that the Spotify web player's song progress bar isn't moving even though a song is playing. I'm not sure if it's due to bad UI programming or because of a browser configuration on my end. I'm on Mac OSX; don't know if you are as well.

I've uploaded a screenshot showing this problem:
<img width="659" alt="wrong song" src="https://cloud.githubusercontent.com/assets/12530197/21821604/cd12db0a-d739-11e6-92c2-d70cbdf23c47.png">

As you can see (and I can attest to this), the actual song being played is "Walking Along ...", as shown by the playing icon next to the song in the playlist, but the player UI still shows the last song, "Summer Sunlight". Accordingly, the extension's background page shows a new song detected log for "Summer Sunlight" but nothing for "Walking Along ..." (BTW, I'm reporting this behavior with the test zip you uploaded)

Here is a chunk of console log showing that song being skipped:
```
controller.js:253 Tab 83: scrobbling song Hijiri Anze - Summer Sunlight
controller.js:264 Tab 83: scrobbling failed
scrobbleCB @ controller.js:264
(anonymous) @ lastfm.js:360
(anonymous) @ lastfm.js:113
(anonymous) @ chromeStorage.js:26
target.(anonymous function) @ extensions::SafeBuiltins:19
safeCallbackApply @ extensions::sendRequest:21
handleResponse @ extensions::sendRequest:74
controller.js:84 Tab 83: state update: only currentTime has changed
controller.js:84 Tab 83: state update: only currentTime has changed
controller.js:84 Tab 83: state update: only currentTime has changed
controller.js:84 Tab 83: state update: only currentTime has changed
controller.js:84 Tab 83: state update: only currentTime has changed
controller.js:84 Tab 83: state update: only currentTime has changed
controller.js:84 Tab 83: state update: only currentTime has changed
controller.js:84 Tab 83: state update: only currentTime has changed
controller.js:84 Tab 83: state update: only currentTime has changed
controller.js:84 Tab 83: state update: only currentTime has changed
controller.js:84 Tab 83: state update: only currentTime has changed
controller.js:84 Tab 83: state update: only currentTime has changed
controller.js:84 Tab 83: state update: only currentTime has changed
controller.js:84 Tab 83: state update: only currentTime has changed
controller.js:97 Tab 83: new track state: {"track":"Shade Underneath the Trees","artist":"Hijiri Anze","album":null,"uniqueID":null,"duration":130,"currentTime":0,"isPlaying":true,"url":"https://play.spotify.com/user/1234883419/playlist/139DBPJS8qz8Q3zcIXtNkw","trackArt":"https://d3rt1990lpmkn.cloudfront.net/unbranded/ded5723e60bca874c0fd756de23511739e12a887"}
```

**Comment by alexesprit** [comment] 2017-01-10 19:58
@ftkftw so I guess Spotify scrobbling is working now? The Spotify UI issues are not related to the extension.

> However, the extension never prompted me to login to my lastfm account after installing it, so I don't know how useful it is to reauthenticate the extension, if reauthenticating doesn't seem to involve user authentication.

It shoud prompt you. Maybe you disabled Chrome notifications in MacOS somehow? How did you authenticated with Last.fm before?

**Comment by ftkftw** [comment] 2017-01-10 20:12
@alexesprit If by working you mean it turns green, yeah, it never stopped working in that sense for me. However, whatever happened to the UI/browser in the last month or so basically broke Spotify web player scrobbling for me.

Desktop notifications are a hit or miss for me. Back when scrobbling was still consistent, it would go for an hour or more without notifications, and then all of a sudden several "song xxx is scrobbling" notifications pop up all at once. It wasn't a big issue for me since I have my lastfm profile page set to auto-refresh.

I now just turned on notifications for all sites, will see if that makes any difference. I don't recall touching this setting at all and was still able to get the scrobbling notifications as mentioned above.

**Comment by alexesprit** [comment] 2017-01-10 20:22
> If by working you mean it turns green, yeah, it never stopped working in that sense for me.

Aah, ok.

Let's wait what @HZNetworks will say about the fix.

**Comment by ftkftw** [comment] 2017-01-10 20:40
Well, thanks for spending time helping me diagnose the issue. Guess I'll go back to the Spotify desktop app for now; sure gonna miss the ad blocking ( ͡° ͜ʖ ͡°)

**Comment by ftkftw** [comment] 2017-01-11 00:24
I think I found the notification bug. I always use Chrome in full screen mode; just now, I switched out of full screen mode, and I am able to see the Chrome notification prompting me to authenticate with lastfm. If I switch back to full screen mode and repeat the same steps I did, I don't see the notification. Hope this helps someone else who's in the same situation.

**Comment by RadianM** [comment] 2017-01-17 18:12
I'm preparing to try out the spotify-test.zip extension but first I'd like to figure out how to unlink the scrobbler from last.fm! When I granted it permission, last.fm said permission could be revoked from my last.fm settings. Nowhere can I find any such facility.

**Comment by alexesprit** [comment] 2017-01-17 18:16
@RadianM I haven't find such option in Last.fm settings. So, I don't worry about this and just allow Last.fm access everytime.

**Comment by RadianM** [comment] 2017-01-17 21:22
OK, that's working well for me :-)

**Comment by alexesprit** [comment] 2017-01-18 06:08
@RadianM sounds good.

**Comment by alexesprit** [comment] 2017-03-12 14:41
I'm closing this issue because looks like new Spotify player is default for most users; the issue is not related to current web player.

**Closed by alexesprit** 2017-03-12 14:41 UTC
Labels: 1: NEEDS CONFIRM, 2: BUG, 3: CONNECTOR
