### ISSUE TITLE
Pandora.com stops scrobbling

### ISSUE THREAD

**Issue by vherever** [david-sabata/web-scrobbler#1194] opened 2016-12-10 21:23 UTC
Hello! It  seems to be some problem with new pandora (just reworked a few days ago)

![pandora-issue](https://cloud.githubusercontent.com/assets/4949404/21076245/50ba8ad4-bf2f-11e6-98d7-1f2644623065.jpg)

**Comment by alexesprit** [comment] 2016-12-11 06:31
Can't reproduce this. Have you any additional information?

Is extension working on other websites for you?

**Comment by Djidiouf** [comment] 2016-12-15 12:12
I have the same issue and the extension is working fine on Google Play.

**Comment by vherever** [comment] 2016-12-15 12:49
Also I tried to test it on the other computer. The same problem. Youtube scrobbling works great.

**Comment by alexesprit** [comment] 2016-12-15 14:55
@Djidiouf what about log of background page?

**Comment by alexesprit** [comment] 2016-12-15 14:57
I don't know how you break Pandora scrobbling, but comments like 'It doesn't work' doesn't resolve the problem.

**Comment by Djidiouf** [comment] 2016-12-16 00:15
@alexesprit Sorry?

> I don't know how you break Pandora scrobbling

There is not that much room for us to 'break' pandora scrobbling as a regular user. Don't assume it's the user fault when your code is failing somewhere until it's demonstrated.

And where did you see 'It doesn't work' without any other comments/logs? Perhaps those don't give you the information you need though you specifically asked if the scrobbler was working on other websites...

You are not helping your project by reacting like that. Bye

**Comment by f1u77y** [comment] 2016-12-16 01:18
Extension works fine for me

(and that logging is misleading: I don't know if `#playbackControl` was finally found on the page in @Djidiouf's case)

**Comment by alexesprit** [comment] 2016-12-16 03:46
@Djidiouf I just wanted to get something like 'steps to reproduce this bug'. Logs w/o explaining your actions is not much useful.

E.g. what does @vherever do to make the tab dissapear (according to logs, the tab with Pandora website is missing while injecting the connector into Pandora webpage)? How do you make the player element missing on the page?

I don't ever know what is the 'new pandora'. It's still the same for me.

**Comment by f1u77y** [comment] 2016-12-16 05:04
@alexesprit 
> I don't ever know what is the 'new pandora'. It's still the same for me.

They could update it for certain region. At least they provide their service only for 3 countries, so they could do smth similar with new design.

Or, alternatively, they could add their new design for some subset of registered users.

**Comment by alexesprit** [comment] 2016-12-16 05:21
@f1u77y but the log that posted by @vherever is really strange. I'm not sure if it's related to the new design of Pandora.

**Comment by f1u77y** [comment] 2016-12-16 05:36
@alexesprit I'm almost sure that this log is unrelated but @Djidiouf's log shows that `#playbackControl` not found while for me it's found.

And as I've said before, the logging here is misleading a little. It could log that player element is not found and then find it with `MutationObserver`

**Comment by LiveBeef** [comment] 2017-01-13 07:07
Can confirm that pandora doesn't work at all for me. Let me know how and I'll provide relevant logging, etc.

**Comment by willrun4fun** [comment] 2017-01-13 14:57
Pandora not working for me either.

**Comment by alexesprit** [comment] 2017-01-16 13:11
We won't fix Pandora until we find out how to switch to that 'new Pandora' website.

On the other side, someone could provide a saved HTML player page of Pandora, so I can try to fix it.

**Comment by LiveBeef** [comment] 2017-01-17 01:44
Are you just talking about a saved copy of the webpage? Got you here if that's what you're asking for

[pandora.zip](https://github.com/david-sabata/web-scrobbler/files/709803/pandora.zip)

**Comment by alexesprit** [comment] 2017-01-17 03:28
@LiveBeef yes, thanks, I was talking about the copy of the page.

Could you install the extension from this zip: https://github.com/alexesprit/web-scrobbler/archive/update-pandora.zip and check how it works?

**Comment by LiveBeef** [comment] 2017-01-17 07:00
No change, it still does not recognize there is a song playing

**Comment by alexesprit** [comment] 2017-01-17 13:24
What about logs?

**Comment by alexesprit** [comment] 2017-01-17 13:31
I updated the zip file. Could you check the extension again?

**Comment by alexesprit** [comment] 2017-01-17 14:36
Should work fine in the extension from the zip I posted above.
![image](https://cloud.githubusercontent.com/assets/1119267/22024541/5ad8ea5a-dcdb-11e6-88c9-df2da63b1760.png)

Would be great if someone confirms that it works for them.

**Comment by LiveBeef** [comment] 2017-01-18 00:17
Confirmed working. Thanks!

**Comment by alexesprit** [comment] 2017-01-18 06:06
@LiveBeef nice, thanks.

Will be available in the next release.

**Closed** 2017-01-18 06:05 UTC
Labels: 1: CONFIRMED, 1: DISCUSSION, 2: BUG, 3: CONNECTOR
