### ISSUE TITLE
Logic of scrobbling repeated songs

### ISSUE THREAD

**Issue by f1u77y** [david-sabata/web-scrobbler#1141] opened 2016-11-09 14:57 UTC
It can produce a bit wrong results. For instance: user listens track from 0% to 90%(and it scrobbles once), then he goes back to 10% and listens to 90% again(and song does not scrobble again). I think song should be scrobbled twice in this case(at least I've seen such behaviour in all(or most) scrobblers that I've ever used)
**UPD** goes back to ~~0%~~ **10%**

**Comment by alexesprit** [comment] 2016-11-09 15:23
Perhaps I didn't understand the problem, but the controller won't recognize repeating of song until these conditions are true:
1. the connector has implemented `getCurrentTime`;
2. the connector is really processing change of current time;
3. the controller received song duration from the connector or Last.fm.

Of course, websites should have a seekable progress element to support this feature.

About 3rd point: defined duration selector or implemented `getDuration` function doesn't mean the connector parsed song duration (this is sort of connector issue).

I've just checked this behaviour on Youtubify website, the extension properly recognizes repeats and scobbles repeated songs.

I assume the issue is related to some buggy connectors, and not the core.

**Comment by f1u77y** [comment] 2016-11-09 15:43
> these conditions
I checked that with VK(which satisfies all conditions)

I've noticed that issue not when using scrobbler but when browsing source code for trying to understand it's [repeat detection logic](https://github.com/david-sabata/web-scrobbler/blob/master/core/background/controller.js#L74). If I understand it right, it detects repeats when `onStateChanged()` is called on last or first 5% of the song. (hmm, I was not right when said "goes back to **0%**" will update the orginal post)

**Comment by alexesprit** [comment] 2016-11-09 15:53
> If I understand it right, it detects repeats when onStateChanged() is called on last or first 5% of the song.

It detects repeat when `onStateChanged` is called and `currentSong.isNearEnd()` returns true (actually this is a previous song) and `isNewStateNearStart` (currentTime is <= 5%) is true too. The connector performs this check on every DOM change (or every 500 ms, if DOM often changes).

**Comment by alexesprit** [comment] 2016-11-09 15:55
So I guess you're suggesting to update the condition by increasing the start limit to 10%, right?

**Comment by f1u77y** [comment] 2016-11-09 16:07
Yup, and if user listened to 90% and then began to listen again from 10%, this logic won't detect repeat(but i think it should)

Also, it depends on frequency of DOM(or sometime other king of) changes much, which, I think, is also bad.

No, I suggest not to use these limits at all(this seems a hack to me and there are some situation when this logic should detect scrobbles but doesn't do it)

I suggest not to detect repeats at all but scrobble each time when playing time hits `duration * (k + scrobblePercentage)` where `k` is an integer and `0.5 <= scrobblePercentage <= 1` is some constant with self-explaining name.

**Comment by alexesprit** [comment] 2016-11-09 16:36
> I suggest not to detect repeats at all but scrobble each time when playing time hits duration * (k + scrobblePercentage) where k is an integer and 0.5 <= scrobblePercentage <= 1 is some constant with self-explaining name.

In this case the user can seek to `duration * (k + scrobblePercentage)` seconds, so the song will scrobble immediately.

**Comment by f1u77y** [comment] 2016-11-09 16:41
I'm not talking about `currentTime` but about "playing time" (no matter in what position the slider is)

**Comment by alexesprit** [comment] 2016-11-09 16:55
Seems like I got you mean.

**Comment by f1u77y** [comment] 2016-11-10 07:44
Do you mean we should reset "playing time" on *real* track change? If so, that's easy enough.

**Comment by alexesprit** [comment] 2016-11-10 08:58
There's no real track change it this case, because it's the same track. That's why that condition with that 5% and 95% is used.

**Comment by f1u77y** [comment] 2016-11-10 10:32
I'm talking about something like [this](cb8d2f8a8b0d5930584e5a781d27edd46ebebcc9)

**Comment by alexesprit** [comment] 2016-11-11 03:52
I understood your idea.

I've checked out your branch and tested replays. The `replayDetectionTimer` triggers before the song is ended. That's strange.

**Comment by f1u77y** [comment] 2016-11-11 04:15
That could be caused by 2 reasons:
1) Duration of song is rounded down, which causes timer to trigger a bit earlier than song ends(could be fixed by triggering timer a second later than it does now; that's a hack but we can't do better if durtion is rounded down)
2) Connector thinks that song is playing when it is buffering(it's so at least for VK; should be very common issue)

**Comment by alexesprit** [comment] 2016-11-11 04:23
The timer triggers on about ~80-90% of playing progress. The song started playing immediately (±1 sec); also, `onProcessed` is called with some delay after the connector recognizes the song is playing that makes the timer to trigger later. Seems like there's another reason. I will try to find out why it happens.

**Comment by f1u77y** [comment] 2016-11-11 05:01
> `onProcessed` is called with some delay after the connector recognizes the song is playing that makes the timer to trigger later.

But `timer.start()` is called immidiately in `onStateChanged()`, and it sets the `startedOn` value, so timer won't trigger later even if delay is very big.

Also, for me the error is about 1-2 seconds, which could be caused by rounding error(that presents in timer.js, which rounds all to seconds)

**Comment by f1u77y** [comment] 2016-11-11 05:14
For now the best idea I can propose is separate behaviour for replaying tracks and detecting new songs. Exactly: do nothing except restarting the two timers and setting status to "now playing" on song replay.

**Comment by alexesprit** [comment] 2017-06-17 15:12
Fixed in #1200.

**Closed by alexesprit** 2017-06-17 15:12 UTC
Labels: 1: DISCUSSION
