### ISSUE TITLE
Seems to be broken for Google Play Music with today's new UI release

### ISSUE THREAD

**Issue by chaddjohnson** [david-sabata/web-scrobbler#603] opened 2015-05-15 03:02 UTC
Might be a red herring, but, this plugin was working for me before today. Google released an updated UI to its Google Play Music, and scrobbling no longer seems to work with this plugin.

**Comment by brycied00d** [comment] 2015-05-15 05:43
:+1: Can confirm. It still gets the artist correctly but can't get the track name, at least based on the blanks in the manual-input popup.

**Comment by brycied00d** [comment] 2015-05-15 05:44
This is a duplicate of #602

**Closed** 2015-05-15 08:05 UTC
Labels: 4: DUPLICATE
