### ISSUE TITLE
Keep seeing the "connect your last.fm account" notification

### ISSUE THREAD

**Issue by eldonzo** [david-sabata/web-scrobbler#981] opened 2016-06-02 21:26 UTC
I succesfully connected the extension to my last.fm account and it scrobble correctly, but I keep seeing the "connect your last.fm account" notification every time I start Chrome.

**Comment by gilmatic** [comment] 2016-06-04 18:13
Came here to report the same.

+1

**Comment by mi1ez** [comment] 2016-06-12 12:34
Me too. 
Chome Version 51.0.2704.84 (64-bit) (Linux)
Last.fm Scrobbler 1.57

**Comment by Forevian** [comment] 2016-06-17 07:37
Also happens for me using Chrome 51.0.2704.84 m (64-bit) on Windows 10

**Comment by david-sabata** [comment] 2016-08-07 20:29
One of the commenters in #990 suggested that this happens when using Chrome/L.FM from multiple computers.

Can anyone affected confirm usage of multiple devices? 
Or a counter-argument, is anyone affected using just single device?

**Comment by ifthenelse** [comment] 2016-08-07 20:38
I am using the Last.fm Scrobbler on a single Chrome installation (stable) and on a single device, which happens to be a Macbook running OSX 10.11.6. I remember it happening with 10.10.X also.
I just quit and restarted Chrome, after a bunch of second the pop-up prompted me to re-authenticate the extension.

**Comment by Forevian** [comment] 2016-08-07 20:41
Definitely using multiple devices, yes. However, I haven't been experiencing this issue lately. After reporting it, the problem just disappeared. Don't remember when exactly -- usually I don't recognize when things work properly :) I guess it was perfect in the last couple of weeks.

**Comment by mi1ez** [comment] 2016-08-08 00:27
Does the same for me in both Windows and Linux.

**Comment by tjharman** [comment] 2016-08-08 04:13
I am using Last.FM on multiple PC's and encounter this issue.
1 Windows 10 laptop I have, it's not a problem.
But a Linux laptop and my new Windows 10 laptop both exhibit the issue.

It's like it's something to do with later version of Chrome - the Laptop that never asks me would have authenticated to Last.FM ~1 year ago.  My Linux laptop and my new Windows PC are both within the last ~2 weeks.

Hope this helps.

**Comment by alexesprit** [comment] 2016-08-08 07:16
Are you guys able to provide some logs?

I'm investigating this problem, but I have no idea how to reproduce and fix it.

How to collect proper logs:
1. Do clean install of the extension.
2. Authenticate via the notification shown after install.
3. Go to `chrome://extensions/` and enable 'Developer mode' option.
4. Look for 'Last.fm Scrobbler' and click on a 'background page' link.
5. Select 'Console' tab in the opened window and copy logs to some text document.
6. Restart your browser.
7. Open 'background page' again, copy logs and append it to previous ones.
8. Paste all logs here.

**Important note**:
Unfortunately, the extension doesn't hide token (private data) in one place.
So, before publishing your logs please find a text like
```xml
getToken response: <?xml version="1.0" encoding="utf-8"?>
<lfm status="ok">
  <token>es7e64sdfa8f5e6sse81bssa31928e8assf</token>
</lfm>
```
and replace the text inside `<token>` tags to something else (like 'xxx' or '***'):
```xml
getToken response: <?xml version="1.0" encoding="utf-8"?>
<lfm status="ok">
  <token>xxx</token>
</lfm>
```

**Comment by eldonzo** [comment] 2016-08-08 23:40
Hi Alexsprit, here is my log after your instructions:

```
chrome.storage.local = {"Core":{"appVersion":"1.57"},"LastFM":{"sessionID":null,"token":null}}
lastfm.js:52 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
lastfm.js:56 getToken response: <?xml version="1.0" encoding="utf-8"?>
<lfm status="ok">
  <token>xxx</token>
</lfm>

notifications.js:181 Notification onClicked: 6BBA00EC-1749-4A24-AEC4-054BD0E53AFF

---------------------------

chrome.storage.local = {"Core":{"appVersion":"1.57"},"LastFM":{"sessionID":null,"token":"xxxxxbba85fcec818bf8e3784b65ddc6"}}
https://ws.audioscrobbler.com/2.0/?method=auth.getsession&api_key=d9bb1870d…cec818bf8e3784b65ddc6&api_sig=fca8b56ffcbf52c80cd7b17960ad4931&format=json Failed to load resource: the server responded with a status of 403 (Forbidden)
lastfm.js:145 auth.getSession failed: Forbidden, error(anonymous function) @ lastfm.js:145
lastfm.js:93 Failed to trade token for session - the token is probably not authorized
lastfm.js:52 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
lastfm.js:56 getToken response: <?xml version="1.0" encoding="utf-8"?>
<lfm status="ok">
  <token>xxx</token>
</lfm>
```

**Comment by alexesprit** [comment] 2016-08-09 01:11
Strange. Looks like you didn't allow access to Last.fm account, but you did it, right?

Are tokens the same or are they different in these log parts?
```xml
<lfm status="ok">
  <token>xxx</token>
</lfm>
```
and
```
chrome.storage.local = {"Core":{"appVersion":"1.57"},"LastFM":{"sessionID":null,"token":"xxxxxbba85fcec818bf8e3784b65ddc6"}}
```

**Comment by eldonzo** [comment] 2016-08-12 10:33
I'm sorry alexesprit, I think I missed one step... I removed the extension some time ago, after the issue occurred, but now it seems to work fine.
At the time I opened the issue I tried to remove and add the extension back, clear cache and cookie and anything else I could think, but nothing worked, now I don't see the notification, so I guess it's fixed.

**Comment by ex47** [comment] 2016-08-12 12:00
@eldonzo close the issue then

**Comment by Kepee** [comment] 2016-08-23 19:27
Removing and then reinstalling the extension seems to have fixed this issue for me.
I re-installed Chrome a week ago and the problem appeared then, could it have something to do with the extension having some cached data somewhere that is left behind when Chrome is uninstalled, and then that data messes things up when Chrome is installed and Chrome automatically installs the extension?

I guess I should have taken the logs _before_ I reinstalled the extension. Now that it's working I suppose there's no point providing any logs either.

**Comment by ifthenelse** [comment] 2016-08-24 08:27
Removing and reinstalling the extension works for me too.
However I didn't try to remove and reinstall Chrome.

**Comment by inverse** [comment] 2016-08-24 16:53
Removing and reinstalling the extension worked for me too. I noticed the issue when I first logged in to my browser when the extensions got synced.

**Comment by alexesprit** [comment] 2016-08-24 16:55
Seems like old wrong token is set while syncronization.

**Comment by leaskovski** [comment] 2016-09-20 13:09
Im pretty certain I see this message because of the fact that I have chrome installed and signed in to across multiple computers.  As soon as I uninstall from one machine and reinstall, then approve that machine to connect, the other machines start showing this behaviour.  I guess this is because that one machine gets the token for the approved API connection, and thus this token isn't valid or isn't able to be used on the other machines?

**Comment by alexesprit** [comment] 2016-09-20 13:28
Tokens are not stored in the extension storage since they're approved. So retrieving a new token on new machine shouldn't break sessions on other machines.

**Comment by alexesprit** [comment] 2016-09-20 17:36
Ok, I've just tried to reproduce this issue again, but I have no luck. Here are my steps.

**Part one - first PC (Win10/Chrome 53.0.2785.116m)**
1. Do clean install of Chrome.
2. Log into Google account.
3. Install the extension from Chrome Web Store.
4, Click on the auth notification.
5. Log into Last.fm. Because Last.fm redirects to user profile page after logged in instead of asking for permissions, I should restart Chrome and click on the notification again. 
6. Ok, restart Chrome, click on the notification.
7. Grant access to Last.fm.
8. Test scrobbling (I used Youtubify for this purpose). Make sure some song is scrobbled (the song should appear in Last.fm playback history).
9. Restart Chrome to make sure the auth notification is not shown on startup.
Scrobbling work fine, notification isn't shown on startup.

**Part two - second PC (configuration is the same as in first one)**
1. Do steps 1 and 2 from previous part.
2. Wait until sync is done. The extension is synced and shows the auth notification.
3. Do steps 5...9 from previous part.
Everything works well too.

**Part three - check if auth is broken on first PC**
1. Run Chrome. No auth notiifcation is shown on startup.
2. Test scrobbling. Works fine.
Nothing changes, everything still works for me.

**Ok, part four - check if auth is broken on second PC**
1. Run Chrome. No auth notiifcation is shown on startup.
2. Test scrobbling. Works fine again.
Still works perfectly.

Is there something I missed?

So, I guess people do something wrong while authenticating, because:
1. there's no any instruction how to reproduce this issue;
2. this issue is usually is fixed by reinstalling the extension or Chrome.

**Comment by alexesprit** [comment] 2016-09-22 06:29
@leaskovski could you please provide logs of the extension installed on PC where this issue is happening?  You can use this instruction for collecting proper logs: https://github.com/david-sabata/web-scrobbler/issues/981#issuecomment-238158879

**Comment by alexesprit** [comment] 2016-09-24 14:52
I've found a way to break authentication:
1. Click on auth notification.
2. Start listening to some music.
3. Grant access to Last.fm. Now it seems like access is granted. Actually, not, because of step 2.

It happens because Web scrobbler drops the token if API returns an error. Of course, it's enough to reauth to get the extension worked. Don't sure if users break auth by this way on each browser launch, but it could help to understand why continuous notifications are shown.

**Comment by alexesprit** [comment] 2017-08-06 15:43
Closed due to changes of auth process.

**Closed by alexesprit** 2017-08-06 15:43 UTC
Labels: 2: BUG, 3: CORE
