### ISSUE TITLE
Repeating the notification of the same song

### ISSUE THREAD

**Issue by hilgi** [david-sabata/web-scrobbler#1111] opened 2016-10-31 19:14 UTC
For some reason today, when a song stats and I receive the notification on my desktop, it keeps opening and closing the notification, I turned off notifications but I notice the Chrome widget if opening and closing constantly. You can see it in the vid, the notifications were doing the same. 

I see them in the last.fm library but after they are done, they look to be removed. I am playing the web player for amazon music. 

![video0029](https://cloud.githubusercontent.com/assets/16419101/19867980/4af776b6-9f63-11e6-9d7e-1e55ac7a6967.gif)

.

**Comment by alexesprit** [comment] 2016-10-31 19:55
Is this happening only with Amazon? Can you please scrobble the music from other websites (e.g. Youtube)?

It's also would be super cool if you provide the extension logs. You can use [this howto](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension) to get proper logs. In this case it's enough to reproduce the extension icon blinking, collect logs and paste them to some pastebin service.

**Comment by hilgi** [comment] 2016-10-31 20:06
It did not do it with Youtube. 

I saved the log, where do I add it?

**Comment by alexesprit** [comment] 2016-10-31 20:11
You can use http://pastebin.com/index.php, for example, to paste all your logs and send the paste URL to this thread.

If you are not familiar with pastebin services, you still can provide logs by sending them in comment. But Github doesn't collapse long text, so pastebin is preferred.

**Comment by hilgi** [comment] 2016-10-31 20:39
Sorry for my lack of knowledge but how do I copy the log to send it to paste bin? Thanks,

**Comment by hilgi** [comment] 2016-11-02 17:02
I have the log, I just don't see how to copy and paste it.

**Comment by alexesprit** [comment] 2016-11-02 17:15
The log is just a text, select it all, then right-click and select "Copy". Now you can paste it here or on pastebin by right-clicking and choosing "Paste".

**Comment by hilgi** [comment] 2016-11-02 17:26
Is this it? http://pastebin.com/m2Vi7QfT

**Comment by alexesprit** [comment] 2016-11-02 17:34
Yes, it is.

But you said the issue is happening when you listen to music on Amazon, right? I see you listened to music on Youtube in the log. Is the extension icon blinking too in this case?

**Comment by alexesprit** [comment] 2016-11-02 17:48
Seems like I found a way to reproduce the issue.

**Comment by hilgi** [comment] 2016-11-02 17:49
The blinking is only Amazon, I not YouTube.

**Comment by alexesprit** [comment] 2016-11-02 18:29
Ok, I got it.

I've made an attempt to fix the issue. Can you please ckeck if it's resolved? https://github.com/alexesprit/web-scrobbler/archive/fix-new-state.zip
Just install it as an [unpacked extension](https://github.com/david-sabata/web-scrobbler#unpacked-extension) and try to scrobble songs from Amazon. Don't forget to disable the extension installed from Chrome Web store first!

**Comment by hilgi** [comment] 2016-11-02 18:52
Looks like it worked! Thanks! Do you have a bitcoin address?

**Comment by alexesprit** [comment] 2016-11-02 18:54
Glad it's working for you :)! No, I don't.

**Comment by hilgi** [comment] 2016-11-02 18:59
Well you should :-) https://airbitz.co/bitcoin-wallet/

**Comment by inverse** [comment] 2016-11-02 19:26
:+1: vote on getting bitcoin

**Comment by hilgi** [comment] 2016-11-04 16:57
Chrome said to turn off developer mode, I did, then it wasn't scrobbling. I turned it back on and it is blinking again.

**Comment by alexesprit** [comment] 2016-11-05 07:36
Seems like it's blinking because you use the extension from Web store, not the unpacked one.

**Comment by alexesprit** [comment] 2016-11-09 20:18
@hilgi should be fixed in new release.

**Comment by alexesprit** [comment] 2016-12-21 07:41
I'll close this issue, because it's reproduced and fixed. Feel free to reopen the issue, if the extension still doesn't work for you properly.

**Closed by alexesprit** 2016-12-21 07:41 UTC
Labels: 2: BUG, 3: CORE
