### ISSUE TITLE
Pocket Casts Web Client Support

### ISSUE THREAD

**Issue by nswint** [david-sabata/web-scrobbler#1510] opened 2017-11-24 05:07 UTC
Requesting Pocket Casts Web Client Support
URL
https://play.pocketcasts.com/

### Steps to reproduce (for bugs)

1.
2.
3.

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser name and version:

**Comment by alexesprit** [comment] 2017-11-24 09:49
Closing this as a duplicate of #1419.

**Closed by alexesprit** 2017-11-24 09:49 UTC
