### ISSUE TITLE
Chrome extension is not working on the new hypemachine

### ISSUE THREAD

**Issue by harrypedro** [david-sabata/web-scrobbler#1343] opened 2017-06-23 17:25 UTC
Extension stopped working on hypemachine since is changed a few weeks ago.

**Comment by alexesprit** [comment] 2017-06-24 06:26
Can't reproduce. Have you any additional information?

**Comment by alexesprit** [comment] 2017-09-17 09:00
Closed as outdated.

**Closed by alexesprit** 2017-09-17 09:00 UTC
Labels: 4: INCONCLUSIVE
