### ISSUE TITLE
Scobbler not recognising music from Spotify web player.

### ISSUE THREAD

**Issue by spjcc** [david-sabata/web-scrobbler#1278] opened 2017-04-11 07:14 UTC
### Expected Behavior
Web scrobbler should recognise music being played on open.spotify.com

### Current Behavior
Spotify changed the web player from play.spotify.com to open.spotify.com. Since this change the web scrobbler is not recognising music being played.

### Possible Solution
Adjust scrobbler settings to match new URL used by Spotify web player

### Steps to Reproduce (for bugs)
1.  Open previous spotify URL (play.spotify.com) which then gets redirected to the new URL (open.spotify.com)
2.  Play some music
3.  Scrobbler does not recognise music being played

### Context
How has this issue affected you? My scrobbles are not being tracked

### Environment
* Version used: 1.62.2
* Browser Name and version: Chrome Version 57.0.2987.133 (64-bit)

**Comment by alexesprit** [comment] 2017-04-11 07:27
Duplicate of #1270.

**Closed by alexesprit** 2017-04-11 07:27 UTC
